# /// script
# requires-python = ">=3.11"
# dependencies = ["sympy==1.13.3"]
# ///
"""Freeze the gear-flank contact inputs of design-robustness.md section 1 for wonky-alg.

Run: uv run rust/wonky-alg/tests/data/flank-contacts.py > rust/wonky-alg/tests/data/flank-contacts.txt

The construction is copied from tmp/cadbench/gears/robustness/exact_flank.py
(sha256 3126fc23b6edc5f1a22ae34096ef83b69c01a1b5dad71ef46b97f2b173188b31, 2026-09-28):
one involute flank from the public parameters m 1, z 45, pressure angle 20 deg (no
reference geometry), 6 binary64 points evenly in roll angle, binary64 centripetal
parameters, an EXACT rational natural cubic, and span 0 as a Bezier cubic. Contacts
of span 0 with (a) the circumcircle of three binary64 points on the root circle, as a
3-point skArc gives, and (b) the radial line through its start point.

The file holds the inputs (controls, carriers) and, as an independent route, sympy's
expanded contact polynomials F(C(t)). sympy also states the facts the Rust test
asserts: t = 0 is a simple root, and after deflation no root is left in [0, 1].
"""
import math
from fractions import Fraction as F
import sympy as sp

m, z, pa = 1.0, 45, math.radians(20.0)
rp = m * z / 2
rb = rp * math.cos(pa)
ra = rp + m
rf = rp - 1.25 * m
rs = max(rb, rf)
inv = lambda a: math.tan(a) - a
theta_b = math.pi / (2 * z) + inv(pa)


def roll(r):
    return math.sqrt(max(r * r / (rb * rb) - 1.0, 0.0))


def inv_pt(t):
    r = rb * math.sqrt(1 + t * t)
    ang = theta_b - (t - math.atan(t))
    return (r * math.cos(ang), r * math.sin(ang))


t0, t1 = roll(rs), roll(ra)
pts = [inv_pt(t0 + (t1 - t0) * k / 5) for k in range(6)]
u = [0.0]
for a, b in zip(pts, pts[1:]):
    u.append(u[-1] + math.sqrt(math.sqrt((b[0] - a[0]) ** 2 + (b[1] - a[1]) ** 2)))


def natural_span0(P, U):
    n = len(P) - 1
    P = [(F(x), F(y)) for x, y in P]
    U = [F(x) for x in U]
    h = [U[i + 1] - U[i] for i in range(n)]
    N = n - 1
    Ms = []
    for comp in range(2):
        a = [F(0)] * N; b = [F(0)] * N; c = [F(0)] * N; d = [F(0)] * N
        for i in range(1, n):
            k = i - 1
            a[k] = h[i - 1]; b[k] = 2 * (h[i - 1] + h[i]); c[k] = h[i]
            d[k] = 6 * ((P[i + 1][comp] - P[i][comp]) / h[i] - (P[i][comp] - P[i - 1][comp]) / h[i - 1])
        for k in range(1, N):
            w = a[k] / b[k - 1]
            b[k] -= w * c[k - 1]; d[k] -= w * d[k - 1]
        x = [F(0)] * N
        x[-1] = d[-1] / b[-1]
        for k in range(N - 2, -1, -1):
            x[k] = (d[k] - c[k] * x[k + 1]) / b[k]
        Ms.append([F(0)] + x + [F(0)])
    inner = []
    for comp in range(2):
        Mi, Mj = Ms[comp][0], Ms[comp][1]
        slope = (P[1][comp] - P[0][comp]) / h[0]
        d0 = slope - h[0] * (2 * Mi + Mj) / 6
        d1 = slope + h[0] * (Mi + 2 * Mj) / 6
        inner.append((P[0][comp] + h[0] * d0 / 3, P[1][comp] - h[0] * d1 / 3))
    return [P[0], (inner[0][0], inner[1][0]), (inner[0][1], inner[1][1]), P[1]]


ctrl = natural_span0(pts, u)
ang0 = math.atan2(pts[0][1], pts[0][0])
root_pts = [pts[0], (rf * math.cos(ang0 + 0.02), rf * math.sin(ang0 + 0.02)),
            (rf * math.cos(ang0 + 0.04), rf * math.sin(ang0 + 0.04))]
ax, ay = map(F, root_pts[0]); bx, by = map(F, root_pts[1]); qx, qy = map(F, root_pts[2])
den = 2 * (ax * (by - qy) + bx * (qy - ay) + qx * (ay - by))
cx = ((ax*ax + ay*ay) * (by - qy) + (bx*bx + by*by) * (qy - ay) + (qx*qx + qy*qy) * (ay - by)) / den
cy = ((ax*ax + ay*ay) * (qx - bx) + (bx*bx + by*by) * (ax - qx) + (qx*qx + qy*qy) * (bx - ax)) / den
r2 = (ax - cx) ** 2 + (ay - cy) ** 2

t = sp.symbols('t')
R = lambda q: sp.Rational(q.numerator, q.denominator)
X = sp.expand(sum(R(ctrl[k][0]) * sp.binomial(3, k) * t**k * (1 - t)**(3 - k) for k in range(4)))
Y = sp.expand(sum(R(ctrl[k][1]) * sp.binomial(3, k) * t**k * (1 - t)**(3 - k) for k in range(4)))
contacts = {
    'arc': sp.expand((X - R(cx))**2 + (Y - R(cy))**2 - R(r2)),
    'line': sp.expand(R(ctrl[0][0]) * Y - R(ctrl[0][1]) * X),
}
q = lambda v: f"{v.numerator}/{v.denominator}"
print("# Generated by flank-contacts.py (see its docstring for provenance); do not edit.")
for k, p in enumerate(ctrl):
    print(f"control {k} {q(p[0])} {q(p[1])}")
print(f"arc {q(cx)} {q(cy)} {q(r2)}")
for name, poly in contacts.items():
    P = sp.Poly(poly, t)
    coefficients = [F(int(c.p), int(c.q)) for c in reversed(P.all_coeffs())]
    assert coefficients[0] == 0, f"{name}: t = 0 must be an exact root"
    deflated = sp.Poly(sp.cancel(poly / t), t)
    assert deflated.eval(0) != 0, f"{name}: t = 0 must be a simple root"
    roots = deflated.count_roots(0, 1)
    assert roots == 0, f"{name}: design-robustness section 1 measured 0 roots after deflation"
    print(f"# sympy: {name} degree {P.degree()}, simple root at t = 0, deflated degree "
          f"{deflated.degree()}, count_roots(0, 1) = {roots}")
    print(f"{name}-poly " + " ".join(q(c) for c in coefficients))
