#!/usr/bin/env python3
"""Independent sympy oracle for the exact-predicate audit (pkg-predicate-audit, 2026-10-02).

Run from the repository root:
    uv run --no-project --with sympy==1.14.0 python rust/wonky-alg/tests/data/predicate-audit.py

Writes (generated, do not edit by hand; the seed is fixed):
    rust/wonky-alg/tests/data/predicate-audit.txt       Sturm counts, isolation, AlgebraicReal cmp/sign_at
    rust/wonky-radical3/tests/data/predicate-audit.txt  Radical3 sign and compare
    rust/wonky-curve/tests/data/radical-audit.txt       Radical (multiquadratic) sign and denesting
    rust/wonky-bool/tests/data/a1-paves-audit.txt       a1::roots quadratic and algebraic paves

The oracle never runs the Rust code and never uses Sturm sequences or gcds:
real roots come from sympy's factorization over Q (irreducible factors) and
its continued-fraction isolation, refined here by exact bisection; signs at
irrational roots use exact rational interval evaluation; signs of radical sums
are certified by mpmath interval arithmetic, and an exact zero is proved by
minimal_polynomial(expr) == x. The script also proves symbolically the
identities the Rust predicates rely on and fails if any proof fails.
"""

import functools
import math
import random
import struct
from fractions import Fraction as F
from math import isqrt
from pathlib import Path

import mpmath
import sympy as sp

RUST = Path(__file__).resolve().parents[3]
X = sp.Symbol("x")
rng = random.Random(20261002)


def fmt(q):
    q = F(q)
    return f"{q.numerator}/{q.denominator}"


def sgn(v):
    return (v > 0) - (v < 0)


def header(script_output):
    return [
        "# Generated by rust/wonky-alg/tests/data/predicate-audit.py (sympy "
        + sp.__version__
        + ", seed 20261002); do not edit.",
        "# " + script_output,
    ]


# --------------------------------------------------------------- symbolic proofs


def prove_identities():
    a, b, r, u, v, t = sp.symbols("a b r u v t", real=True)
    # Sign-aware squaring (radical3 exact_sign, Radical field_sign, rational::Quadratic):
    # (A + B sqrt r)(A - B sqrt r) = A^2 - r B^2; for sign(A) = -sign(B) != 0 the
    # conjugate A - B sqrt r has sign(A), so sign(A + B sqrt r) = sign(A) sign(A^2 - r B^2).
    rp = sp.Symbol("rp", positive=True)
    assert sp.expand((a + b * sp.sqrt(rp)) * (a - b * sp.sqrt(rp)) - (a**2 - rp * b**2)) == 0
    # Multiquadratic basis product (radical3 product, Radical field_mul):
    # sqrt(prod_{i in I} r_i) sqrt(prod_{j in J} r_j) = sqrt(prod_{I xor J}) prod_{I and J} r_k.
    rs = sp.symbols("r0 r1 r2", positive=True)
    root = lambda mask: sp.Mul(*[sp.sqrt(rs[k]) for k in range(3) if mask >> k & 1])
    for i in range(8):
        for j in range(8):
            lhs = root(i) * root(j)
            rhs = root(i ^ j) * sp.Mul(*[rs[k] for k in range(3) if (i & j) >> k & 1])
            assert sp.simplify(lhs - rhs) == 0
    # Denesting (Radical::quadratic_sqrt): with N = a^2 - b^2 r = s^2, u = (a + s)/2,
    # v = (a - s)/2: (sqrt u + sqrt v)^2 = a + 2 sqrt(uv) and 4uv = a^2 - s^2 = b^2 r.
    s = sp.Symbol("s", nonnegative=True)
    uu, vv = (a + s) / 2, (a - s) / 2
    assert sp.expand(uu + vv - a) == 0
    assert sp.expand(4 * uu * vv - (a**2 - s**2)) == 0
    # Cramer / triple-product corner (wonky-blend chamfer intersection).
    na, nb, nc = (sp.Matrix(sp.symbols(f"{p}0:3")) for p in "abc")
    da, db, dc = sp.symbols("da db dc")
    det = na.dot(nb.cross(nc))
    point = (da * nb.cross(nc) + db * nc.cross(na) + dc * na.cross(nb)) / det
    for n, d in [(na, da), (nb, db), (nc, dc)]:
        assert sp.simplify(n.dot(point) - d) == 0
    # Chamfer spring point: |w t / sqrt(t.t)|^2 = w^2.
    tv = sp.Matrix(sp.symbols("t0:3", real=True))
    w = sp.Symbol("w", positive=True)
    assert sp.simplify((w * tv / sp.sqrt(tv.dot(tv))).dot(w * tv / sp.sqrt(tv.dot(tv))) - w**2) == 0
    # Projective half-angle circle chart (a1 Branch::Circle): unit circle, and
    # a quadric pulled back has degree <= 4, so a seam root has multiplicity 4 - deg.
    cx, cy, den = 1 - t**2, 2 * t, 1 + t**2
    assert sp.simplify(cx**2 + cy**2 - den**2) == 0
    # Plane x revolution (a1 plane_revolution, parallel cylinders): with
    # p = n rhs / n2 + u (-ny, nx), |p|^2 = rhs^2 / n2 + n2 u^2.
    nx, ny, rhs = sp.symbols("nx ny rhs", real=True)
    n2 = nx**2 + ny**2
    px, py = nx * rhs / n2 - u * ny, ny * rhs / n2 + u * nx
    assert sp.simplify(px**2 + py**2 - (rhs**2 / n2 + n2 * u**2)) == 0
    # Coaxial meridian reduction (a1 revolutions): x^2 + y^2 = (base + slope z)^2
    # substituted into x^2 + y^2 + c3 z + c9 z^2 + c0.
    base, slope, c0, c3, c9, z = sp.symbols("base slope c0 c3 c9 z")
    lhs = (base + slope * z) ** 2 + c3 * z + c9 * z**2 + c0
    rhs2 = (c0 + base**2) + (c3 + 2 * base * slope) * z + (c9 + slope**2) * z**2
    assert sp.expand(lhs - rhs2) == 0
    # Power <-> Bernstein basis change (wonky-alg bernstein.rs), degrees 0..6.
    for n in range(7):
        coeffs = sp.symbols(f"p0:{n + 1}")
        power = sum(coeffs[j] * t**j for j in range(n + 1))
        bern = [
            sum(sp.binomial(k, j) / sp.binomial(n, j) * coeffs[j] for j in range(k + 1))
            for k in range(n + 1)
        ]
        back = sum(bern[k] * sp.binomial(n, k) * t**k * (1 - t) ** (n - k) for k in range(n + 1))
        assert sp.expand(back - power) == 0
    return 9


# ------------------------------------------------------------- algebraic roots


def ev(c, q):
    acc = F(0)
    for coef in reversed(c):
        acc = acc * q + coef
    return acc


def imul(a, b):
    p = [a[0] * b[0], a[0] * b[1], a[1] * b[0], a[1] * b[1]]
    return min(p), max(p)


def iv_eval(c, s, t):
    lo = hi = F(0)
    for coef in reversed(c):
        lo, hi = imul((lo, hi), (s, t))
        lo, hi = lo + coef, hi + coef
    return lo, hi


class Root:
    """A rational root, or (irreducible monic f, index, isolating interval)."""

    def __init__(self, value=None, f=None, index=None, iv=None):
        self.value, self.f, self.index, self.iv = value, f, index, iv

    def rational(self):
        return self.f is None

    def key(self):
        return ("q", self.value) if self.rational() else ("a", tuple(self.f), self.index)

    def refine(self):
        s, t = self.iv
        m = (s + t) / 2
        fm = ev(self.f, m)
        assert fm != 0, "irreducible factor of degree >= 2 has no rational root"
        self.iv = (m, t) if sgn(fm) == sgn(ev(self.f, s)) else (s, m)


def coeffs_of(poly):
    return [F(int(c.p), int(c.q)) for c in reversed(poly.all_coeffs())]


def real_roots(expr):
    """Distinct real roots in increasing order with multiplicities."""
    _, factors = sp.factor_list(sp.Poly(expr, X, domain=sp.QQ))
    out = []
    for f, m in factors:
        f = f.monic()
        c = coeffs_of(f)
        if f.degree() == 1:
            out.append((Root(value=-c[0]), m))
            continue
        for index, ((s, t), _) in enumerate(f.intervals()):
            s, t = F(int(s.p), int(s.q)), F(int(t.p), int(t.q))
            assert s < t and sgn(ev(c, s)) * sgn(ev(c, t)) < 0
            out.append((Root(f=c, index=index, iv=(s, t)), m))
    out.sort(key=functools.cmp_to_key(lambda a, b: cmp_roots(a[0], b[0])))
    return out


def cmp_rational(root, q):
    if root.rational():
        return sgn(root.value - q)
    while root.iv[0] <= q <= root.iv[1]:
        root.refine()
    return -1 if root.iv[1] < q else 1


def cmp_roots(a, b):
    if a.key() == b.key():
        return 0
    if a.rational():
        return -cmp_rational(b, a.value)
    if b.rational():
        return cmp_rational(a, b.value)
    # Distinct monic irreducible factors share no root; equal factors differ by index.
    while True:
        if a.iv[1] < b.iv[0]:
            return -1
        if b.iv[1] < a.iv[0]:
            return 1
        (a if a.iv[1] - a.iv[0] >= b.iv[1] - b.iv[0] else b).refine()


def sign_at(q_coeffs, root):
    if root.rational():
        return sgn(ev(q_coeffs, root.value))
    q = sp.Poly(list(reversed([sp.Rational(c.numerator, c.denominator) for c in q_coeffs])), X)
    f = sp.Poly(list(reversed([sp.Rational(c.numerator, c.denominator) for c in root.f])), X)
    if q.rem(f).is_zero:
        return 0
    while True:
        lo, hi = iv_eval(q_coeffs, *root.iv)
        if lo > 0:
            return 1
        if hi < 0:
            return -1
        root.refine()


def algebra_corpus():
    x = X
    sqrt2_100 = F(isqrt(2 << 200), 1 << 100)
    linear = [
        F(0), F(1), F(-1), F(1, 3), F(1 / 3), F(-7, 5), 1 + F(2) ** -52, 1 - F(2) ** -53,
        F(665857, 470832), sqrt2_100,
    ]
    irreducible = [
        x**2 - 2, x**2 - 3, x**2 - x - 1, x**3 - 2, x**3 - 3 * x + 1, x**4 - 10 * x**2 + 1,
        x**2 - 2 * x + 1 - 2 * sp.Rational(1, 2**120),  # roots 1 +- sqrt2 2^-60
        x**2 + 1, x**2 - sp.Rational(2, 9), 3 * x**3 - x - 1,
    ]
    pool = [x - sp.Rational(q.numerator, q.denominator) for q in linear] + irreducible
    # Binary64-boundary roots. A degree-12 product spanning 2^-1074..2^1023 took
    # 424 s in isolate_real_roots alone (coefficient growth, not a wrong
    # decision); production SSI equations have degree <= 4, so these factors
    # meet at most one other factor and degree 4.
    extreme_linear = [F(2) ** -1074, F(2) ** -1022, F(2) ** 60, -F(2) ** 60, F(2) ** 1023, F(3, 2**70)]
    extreme = [x - sp.Rational(q.numerator, q.denominator) for q in extreme_linear] + [
        x**2 - sp.Rational(1, 2**1073), x**2 - 3 * sp.Integer(2) ** 1000,
    ]

    polys = []
    while len(polys) < 48:
        if len(polys) % 3 == 0:
            factors, limit = [rng.choice(extreme)] + rng.sample(pool + extreme, rng.randint(0, 1)), 4
        else:
            factors, limit = rng.sample(pool, rng.randint(1, 3)), 12
        expr = rng.choice([sp.Integer(1), sp.Integer(-3), sp.Rational(2, 7)])
        for f in factors:
            expr *= f ** rng.choice([1, 1, 1, 2, 3])
        if sp.degree(expr, X) <= limit:
            polys.append(expr)
    # Deliberate shared irrational and rational roots across polynomials.
    polys += [
        (x**2 - 2) * (x - sp.Rational(665857, 470832)),
        (x**2 - 2) ** 2 * (x**3 - 2),
        (x - sp.Rational(sqrt2_100.numerator, sqrt2_100.denominator)) * (x**2 - 3),
        (x**4 - 10 * x**2 + 1) * (x**2 - 2),
        (x - sp.Rational(1, 3)) ** 3 * (x - sp.Rational(F(1 / 3).numerator, F(1 / 3).denominator)),
        (x**2 - 2 * x + 1 - 2 * sp.Rational(1, 2**120)) * (x - 1) ** 2,
        x**5,
        sp.Integer(7),
    ]

    lines = []
    data = []
    for i, expr in enumerate(polys):
        p = sp.Poly(sp.expand(expr), x, domain=sp.QQ)
        c = coeffs_of(p)
        roots = real_roots(expr)
        data.append((c, roots))
        lines.append(f"poly {i} " + " ".join(fmt(v) for v in c))
        lines.append(f"roots {i} " + " ".join(str(m) for _, m in roots))
    counts = certs = cmps = signs = 0
    rationals = [r.value for _, roots in data for r, _ in roots if r.rational()]
    for i, (c, roots) in enumerate(data):
        ends = [r.value for r, _ in roots if r.rational()] + rng.sample(rationals, 4)
        ends += [F(rng.randint(-40, 40), rng.randint(1, 9)) for _ in range(3)]
        for _ in range(8):
            a, b = sorted(rng.sample(ends, 2)) if rng.random() < 0.8 else [rng.choice(ends)] * 2
            pos = [(cmp_rational(r, a), cmp_rational(r, b)) for r, _ in roots]
            open_ = sum(1 for lo, hi in pos if lo > 0 and hi < 0)
            half = 0 if a == b else sum(1 for lo, hi in pos if lo >= 0 and hi < 0)
            closed = sum(1 for lo, hi in pos if lo >= 0 and hi <= 0)
            if a == b:
                open_ = 0
            lines.append(f"count {i} {fmt(a)} {fmt(b)} {open_} {half} {closed}")
            counts += 1
            # Certificate admission (AlgebraicReal::from_interval preconditions).
            at_end = any(lo == 0 or hi == 0 for lo, hi in pos)
            if a == b:
                expect = "ok" if closed == 1 else f"notisolating:{closed}"
            elif at_end:
                expect = "endpoint"
            else:
                expect = "ok" if open_ == 1 else f"notisolating:{open_}"
            mult = "-"
            if expect == "ok":
                mult = str(next(m for (r, m), (lo, hi) in zip(roots, pos) if lo >= 0 and hi <= 0))
            lines.append(f"cert {i} {fmt(a)} {fmt(b)} {expect} {mult}")
            certs += 1
    for _ in range(300):
        i, j = rng.randrange(len(data)), rng.randrange(len(data))
        if not data[i][1] or not data[j][1]:
            continue
        ri, rj = rng.randrange(len(data[i][1])), rng.randrange(len(data[j][1]))
        order = cmp_roots(data[i][1][ri][0], data[j][1][rj][0])
        lines.append(f"cmp {i} {ri} {j} {rj} {order}")
        cmps += 1
    for _ in range(300):
        i, j = rng.randrange(len(data)), rng.randrange(len(data))
        if not data[i][1]:
            continue
        ri = rng.randrange(len(data[i][1]))
        lines.append(f"sign {i} {ri} {j} {sign_at(data[j][0], data[i][1][ri][0])}")
        signs += 1
    total_roots = sum(len(r) for _, r in data)
    summary = (
        f"{len(polys)} polynomials, {total_roots} distinct real roots, {counts} interval counts "
        f"(open/half-open/closed), {certs} certificates, {cmps} cmp, {signs} sign_at"
    )
    return header(summary) + lines, summary


# ------------------------------------------------------------- radical signs

mpmath.mp.prec = 64


def certified_sign(terms):
    """terms: list of (coefficient Fraction, [radicand Fraction...]) meaning c * prod sqrt(r)."""
    for prec in (256, 4096, 32768):
        mpmath.iv.prec = prec
        total = mpmath.iv.mpf(0)
        for c, rads in terms:
            term = mpmath.iv.mpf(c.numerator) / c.denominator
            for r in rads:
                term *= mpmath.iv.sqrt(mpmath.iv.mpf(r.numerator) / r.denominator)
            total += term
        if total.a > 0:
            return 1
        if total.b < 0:
            return -1
    expr = sum(
        sp.Rational(c.numerator, c.denominator)
        * sp.Mul(*[sp.sqrt(sp.Rational(r.numerator, r.denominator)) for r in rads])
        for c, rads in terms
    )
    if expr == 0 or sp.minimal_polynomial(expr, X) == X:
        return 0
    raise AssertionError(f"sign not certified at 32768 bits: {terms}")


def bits(v):
    return f"{struct.unpack('<Q', struct.pack('<d', v))[0]:016x}"


MIN_MAG, MAX_MAG = 1.0e-150, 1.0e150


def in_range(v):
    return v == 0.0 or (abs(v) >= MIN_MAG and abs(v) <= MAX_MAG)


def nearest_double_of(terms):
    mpmath.mp.prec = 200
    s = mpmath.mpf(0)
    for c, rads in terms:
        t = mpmath.mpf(c.numerator) / c.denominator
        for r in rads:
            t *= mpmath.sqrt(mpmath.mpf(r.numerator) / r.denominator)
        s += t
    return float(s)


def dyadic(scale=6):
    return rng.randint(-2**10, 2**10) / 2 ** rng.randint(0, scale)


def sum3_terms(a, ts):
    return [(F(a), [])] + [(F(c), [F(r)]) for c, r in ts]


def radical3_corpus():
    lines = []
    cases = []
    radicands = [0.0, 1.0, 2.0, 3.0, 5.0, 6.0, 8.0, 0.5, 0.25, 12.0, 18.0, 6549.0, 2.0**-60, 3.0 * 2.0**80]
    for _ in range(300):
        ts = [(dyadic(), rng.choice(radicands) if rng.random() < 0.6 else abs(dyadic(20))) for _ in range(3)]
        mode = rng.random()
        if mode < 0.45:
            a = dyadic()
        else:
            a = -nearest_double_of([(F(c), [F(r)]) for c, r in ts])
            a = rng.choice([a, math.nextafter(a, math.inf), math.nextafter(a, -math.inf)])
        cases.append((a, ts))
    # Dependent and equal radicands with exact cancellation.
    for _ in range(60):
        r = rng.choice([2.0, 3.0, 0.75, 5.0 * 2.0**-40, 7.0 * 2.0**40])
        c = dyadic(3)
        k = rng.choice([4.0, 0.25, 9.0, 1.0])
        root_k = {4.0: 2.0, 0.25: 0.5, 9.0: 3.0, 1.0: 1.0}[k]
        ts = [(c, r), (-c / root_k, r * k), (rng.choice([0.0, 0.0, dyadic()]), rng.choice([r, 1.0, 4.0]))]
        cases.append((rng.choice([0.0, 0.0, dyadic(), 2.0**-57]), ts))
    # Range boundary of the admitted binary64 inputs.
    edge = [1e-150, 1e150, 2.0**-498, 2.0**498, 1e-150 * (1 - 2**-52), 1e151, 5e-324, 2.0**-1022, -0.0]
    for v in edge:
        for slot in range(3):
            ts = [(1.0, 2.0), (-1.0, 3.0), (0.5, 5.0)]
            if slot == 0:
                cases.append((v, ts))
            else:
                ts[slot] = (v, ts[slot][1]) if slot == 1 else (ts[slot][0], abs(v))
                cases.append((1.0, ts))
    for a, ts in cases:
        values = [a] + [v for t in ts for v in t]
        if not all(in_range(v) for v in values):
            expect = "out"
        else:
            expect = str(certified_sign(sum3_terms(a, ts)))
        lines.append(f"sum3 {expect} {bits(a)} " + " ".join(f"{bits(c)} {bits(r)}" for c, r in ts))
    n_sum3 = len(cases)
    # General product basis (Radical3::new): sum_mask c_mask prod_{i in mask} sqrt(r_i).
    n_general = 0
    for _ in range(150):
        rs = [rng.choice(radicands[1:12]) for _ in range(3)]
        cs = [dyadic() if rng.random() < 0.7 else 0.0 for _ in range(8)]
        terms = [(F(cs[m]), [F(rs[k]) for k in range(3) if m >> k & 1]) for m in range(8)]
        if rng.random() < 0.5:
            cs[0] = -nearest_double_of(terms[1:])
            terms[0] = (F(cs[0]), [])
        lines.append(
            f"general {certified_sign(terms)} " + " ".join(bits(r) for r in rs) + " " + " ".join(bits(c) for c in cs)
        )
        n_general += 1
    # Dependent product-basis radicands r1 = 4 r0 with an exact zero sum:
    # c sqrt(r0 r1) = 2 r0 c and c' sqrt(r1) = 2 c' sqrt(r0).
    for _ in range(40):
        r0 = rng.choice([2.0, 3.0, 0.75, 5.0])
        rs = [r0, 4.0 * r0, rng.choice([3.0, 7.0, r0])]
        c, c1 = dyadic(3), dyadic(3)
        cs = [-2.0 * r0 * c, c1, -c1 / 2.0, c, 0.0, 0.0, 0.0, 0.0]
        if rng.random() < 0.3:
            cs[0] += rng.choice([2.0**-40, -(2.0**-40)])
        terms = [(F(cs[m]), [F(rs[k]) for k in range(3) if m >> k & 1]) for m in range(8)]
        lines.append(
            f"general {certified_sign(terms)} " + " ".join(bits(r) for r in rs) + " " + " ".join(bits(c) for c in cs)
        )
        n_general += 1
    # compare(x, y): union of active radicands > 3 is the documented degree refusal.
    n_cmp = 0
    for _ in range(200):
        x = cases[rng.randrange(n_sum3)]
        y = (x[0] + dyadic(8), [(c + rng.choice([0.0, dyadic(10)]), r) for c, r in x[1]])
        if rng.random() < 0.4:
            y = cases[rng.randrange(n_sum3)]
        if rng.random() < 0.3:
            perm = rng.sample(x[1], 3)
            y = (x[0] - rng.choice([0.0, 2.0**-50]), perm)
        values = [x[0], y[0]] + [v for t in x[1] + y[1] for v in t]
        if not all(in_range(v) for v in values):
            continue
        active = {F(r) for c, r in x[1] + y[1] if c != 0 and r != 0}
        if len(active) > 3:
            expect = "degree"
        else:
            expect = str(certified_sign(sum3_terms(*x) + [(-c, rads) for c, rads in sum3_terms(*y)]))
        lines.append(
            f"cmp {expect} "
            + " ".join(
                f"{bits(a)} " + " ".join(f"{bits(c)} {bits(r)}" for c, r in ts) for a, ts in (x, y)
            )
        )
        n_cmp += 1
    summary = f"{n_sum3} sum3 signs, {n_general} product-basis signs, {n_cmp} compares"
    return header(summary) + lines, summary


def rational_term():
    num = rng.choice([1, 2, 3, 5, 6, 7, 8, 10, 12, 18, 50, 2**61 - 1, 3**40])
    return F(num, rng.choice([1, 4, 9, 2, 3, 2**64]))


def radical_corpus():
    lines = []
    n_sign = 0
    for _ in range(300):
        k = rng.randint(1, 5)
        terms = []
        for _ in range(k):
            r = rational_term()
            if rng.random() < 0.3 and terms:
                r = terms[-1][1][0] * rng.choice([F(4), F(1, 9), F(25, 4), F(1)])
            terms.append((F(rng.randint(-30, 30), rng.choice([1, 2, 3, 7, 2**70])), [r]))
        if rng.random() < 0.5:
            # Near-cancelling rational part from a continued-fraction convergent.
            approx = F(nearest_double_of(terms)).limit_denominator(rng.choice([10**6, 10**15, 10**30]))
            terms.append((-approx, [F(1)]))
        if rng.random() < 0.1:
            terms.append((-terms[0][0], terms[0][1]))
        expect = certified_sign(terms)
        lines.append(f"sign {expect} {len(terms)} " + " ".join(f"{fmt(r[0] if r else 1)} {fmt(c)}" for c, r in terms))
        n_sign += 1
    n_denest = 0
    for _ in range(150):
        mode = rng.random()
        if mode < 0.5:
            u, v = (F(rng.randint(0, 50), rng.choice([1, 4, 9, 3])) for _ in range(2))
            sgn_b = rng.choice([1, -1])
            # (sqrt u + s sqrt v)^2 = u + v + 2 s sqrt(uv); keep a single radical class.
            a, b, r = u + v, F(2 * sgn_b), u * v
        else:
            a, b, r = F(rng.randint(-20, 40), rng.choice([1, 2, 3])), F(rng.randint(-9, 9), rng.choice([1, 2])), F(rng.choice([2, 3, 5, 6, 7, 8, 12, 18]))
        expr = sp.Rational(a.numerator, a.denominator) + sp.Rational(b.numerator, b.denominator) * sp.sqrt(sp.Rational(r.numerator, r.denominator))
        if expr.is_negative:
            result = "negative"
        else:
            out = sp.sqrtdenest(sp.sqrt(expr))
            parts = sp.Add.make_args(sp.expand(out))
            simple = []
            for p in parts:
                c, rest = p.as_coeff_Mul()
                if rest == 1:
                    simple.append((F(1), F(int(c.p), int(c.q))))
                elif isinstance(rest, sp.Pow) and rest.exp == sp.Rational(1, 2) and rest.base.is_Rational:
                    simple.append((F(int(rest.base.p), int(rest.base.q)), F(int(c.p), int(c.q))))
                else:
                    simple = None
                    break
            result = "none" if simple is None else " ".join(f"{fmt(r_)} {fmt(c_)}" for r_, c_ in simple)
            if simple is not None:
                assert sp.simplify(out**2 - expr) == 0
        lines.append(f"denest {fmt(a)} {fmt(b)} {fmt(r)} {result}")
        n_denest += 1
    summary = f"{n_sign} multiquadratic signs, {n_denest} denesting cases"
    return header(summary) + lines, summary


def paves_corpus():
    lines = []
    n = 0
    specials = [
        [1, -2, 1], [-2, 0, 1], [1, 0, 1], [0, 0, 1], [1, 3], [5], [sp.Rational(1, 4), -1, 1],
        [1 - sp.Rational(1, 2**120) * 2, -2, 1], [-3, 0, sp.Integer(2) ** 200],
        [sp.Rational(-1, 3), 0, 0, 1], [0, -2, 0, 1, 0, 0], [1, -4, 6, -4, 1],
    ]
    polys = [list(map(sp.nsimplify, s)) for s in specials]
    for _ in range(150):
        deg = rng.choice([1, 2, 2, 2, 2, 3, 4])
        if rng.random() < 0.3:
            r = sp.Rational(rng.randint(-20, 20), rng.randint(1, 9))
            c = sp.Poly(sp.Rational(rng.randint(1, 5), rng.randint(1, 3)) * (X - r) ** 2, X).all_coeffs()[::-1]
        else:
            c = [sp.Rational(rng.randint(-30, 30), rng.randint(1, 12)) for _ in range(deg + 1)]
            if c[-1] == 0:
                c[-1] = sp.Integer(1)
        polys.append(c)
    for c in polys:
        p = sp.Poly(list(reversed(c)), X, domain=sp.QQ)
        if p.is_zero:
            continue
        roots = real_roots(p.as_expr())
        parts = []
        if p.degree() <= 2:
            values = sorted(sp.roots(p, filter="R"), key=lambda e: sp.N(e, 60))
            assert len(values) == len(roots)
            for (root, m), value in zip(roots, values):
                base, coeff, rad = sp.Integer(0), sp.Integer(0), sp.Integer(0)
                for term in sp.Add.make_args(sp.expand(value)):
                    k, rest = term.as_coeff_Mul()
                    if rest == 1:
                        base += k
                    else:
                        assert isinstance(rest, sp.Pow) and rest.exp == sp.Rational(1, 2)
                        coeff, rad = k, rest.base
                parts.append(f"{fmt(F(int(base.p), int(base.q)))} {fmt(F(int(coeff.p), int(coeff.q)))} {fmt(F(int(rad.p), int(rad.q)))} {m}")
        else:
            parts = [f"- - - {m}" for _, m in roots]
        lines.append("paves " + " ".join(fmt(F(int(v.p), int(v.q))) for v in reversed(p.all_coeffs())) + " | " + " , ".join(parts))
        n += 1
    summary = f"{n} pave equations"
    return header(summary) + lines, summary


def main():
    proofs = prove_identities()
    outputs = {
        RUST / "wonky-alg/tests/data/predicate-audit.txt": algebra_corpus(),
        RUST / "wonky-radical3/tests/data/predicate-audit.txt": radical3_corpus(),
        RUST / "wonky-curve/tests/data/radical-audit.txt": radical_corpus(),
        RUST / "wonky-bool/tests/data/a1-paves-audit.txt": paves_corpus(),
    }
    print(f"{proofs} identity groups proved symbolically")
    for path, (lines, summary) in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("\n".join(lines) + "\n")
        print(f"{path.relative_to(RUST.parent)}: {summary}")


if __name__ == "__main__":
    main()
