// GENERATED by scripts/native-bridge/gen-wire.mjs. Do not edit.
// Exact U32 wire codecs for Bend JS-target values ({$: Ctor, ...fields},
// Con/Nil lists, F32/U32 as numbers, Bool as booleans).
const f32 = new Float32Array(1), bits = new Uint32Array(f32.buffer);
const fail = message => { throw new RangeError(`wire: ${message}`); };
const enc_U32 = (x, out) => { if (!Number.isInteger(x) || x < 0 || x > 0xffffffff) fail(`U32 expected, got ${x}`); out.push(x); };
const enc_F32 = (x, out) => {
  if (typeof x !== "number") fail(`F32 expected, got ${typeof x}`);
  f32[0] = x;
  if (!Object.is(f32[0], x)) fail(`${x} is not exactly representable as F32`);
  out.push(bits[0]);
};
const enc_Bool = (x, out) => { if (typeof x !== "boolean") fail(`Bool expected, got ${typeof x}`); out.push(x ? 1 : 0); };
const dec_U32 = r => r.take();
const dec_F32 = r => { bits[0] = r.take(); return f32[0]; };
const dec_Bool = r => { const x = r.take(); if (x > 1) fail(`Bool word ${x}`); return x === 1; };
const enc_String = (s, out) => { if (typeof s !== "string") fail(`String expected, got ${typeof s}`); const chars = [...s]; out.push(chars.length); for (const ch of chars) out.push(ch.codePointAt(0)); };
const dec_String = r => {
  const n = r.take(); if (n > r.words.length - r.i) fail("string length exceeds message");
  let s = ""; for (let i = 0; i < n; i++) { const code = r.take(); if (code > 0x10ffff) fail(`Char ${code}`); s += String.fromCodePoint(code); }
  return s;
};
const reader = words => ({ words, i: 0, take() { if (this.i >= this.words.length) fail("truncated"); return this.words[this.i++]; } });

// topology.bend:Coedge
function enc_topology_Coedge(v, out) {
  if (v?.$ !== "Use") fail(`topology.bend:Coedge constructor ${v?.$}`);
  enc_U32(v.edge, out);
  enc_Bool(v.forward, out);
}
function dec_topology_Coedge(r) {
  return { $: "Use", edge: dec_U32(r), forward: dec_Bool(r) };
}

// topology.bend:Edge
function enc_topology_Edge(v, out) {
  if (v?.$ !== "Edge") fail(`topology.bend:Edge constructor ${v?.$}`);
  enc_U32(v.start, out);
  enc_U32(v.end, out);
}
function dec_topology_Edge(r) {
  return { $: "Edge", start: dec_U32(r), end: dec_U32(r) };
}

// geometry.bend:Vec3
function enc_geometry_Vec3(v, out) {
  if (v?.$ !== "V3") fail(`geometry.bend:Vec3 constructor ${v?.$}`);
  enc_F32(v.x, out);
  enc_F32(v.y, out);
  enc_F32(v.z, out);
}
function dec_geometry_Vec3(r) {
  return { $: "V3", x: dec_F32(r), y: dec_F32(r), z: dec_F32(r) };
}

function enc_L_topology_Coedge(xs, out) {
  const at = out.length; out.push(0); let n = 0;
  for (; xs.$ === "Con"; xs = xs.tail, n++) enc_topology_Coedge(xs.head, out);
  if (xs.$ !== "Nil") fail("malformed list");
  out[at] = n;
}
function dec_L_topology_Coedge(r) {
  const n = r.take(); if (n > r.words.length - r.i) fail("list length exceeds message");
  const items = []; for (let i = 0; i < n; i++) items.push(dec_topology_Coedge(r));
  return items.reduceRight((tail, head) => ({ $: "Con", head, tail }), { $: "Nil" });
}
// topology.bend:Face
function enc_topology_Face(v, out) {
  if (v?.$ !== "Face") fail(`topology.bend:Face constructor ${v?.$}`);
  enc_geometry_Vec3(v.origin, out);
  enc_geometry_Vec3(v.normal, out);
  enc_geometry_Vec3(v.x, out);
  enc_L_topology_Coedge(v.boundary, out);
}
function dec_topology_Face(r) {
  return { $: "Face", origin: dec_geometry_Vec3(r), normal: dec_geometry_Vec3(r), x: dec_geometry_Vec3(r), boundary: dec_L_topology_Coedge(r) };
}

function enc_L_geometry_Vec3(xs, out) {
  const at = out.length; out.push(0); let n = 0;
  for (; xs.$ === "Con"; xs = xs.tail, n++) enc_geometry_Vec3(xs.head, out);
  if (xs.$ !== "Nil") fail("malformed list");
  out[at] = n;
}
function dec_L_geometry_Vec3(r) {
  const n = r.take(); if (n > r.words.length - r.i) fail("list length exceeds message");
  const items = []; for (let i = 0; i < n; i++) items.push(dec_geometry_Vec3(r));
  return items.reduceRight((tail, head) => ({ $: "Con", head, tail }), { $: "Nil" });
}
function enc_L_topology_Edge(xs, out) {
  const at = out.length; out.push(0); let n = 0;
  for (; xs.$ === "Con"; xs = xs.tail, n++) enc_topology_Edge(xs.head, out);
  if (xs.$ !== "Nil") fail("malformed list");
  out[at] = n;
}
function dec_L_topology_Edge(r) {
  const n = r.take(); if (n > r.words.length - r.i) fail("list length exceeds message");
  const items = []; for (let i = 0; i < n; i++) items.push(dec_topology_Edge(r));
  return items.reduceRight((tail, head) => ({ $: "Con", head, tail }), { $: "Nil" });
}
function enc_L_topology_Face(xs, out) {
  const at = out.length; out.push(0); let n = 0;
  for (; xs.$ === "Con"; xs = xs.tail, n++) enc_topology_Face(xs.head, out);
  if (xs.$ !== "Nil") fail("malformed list");
  out[at] = n;
}
function dec_L_topology_Face(r) {
  const n = r.take(); if (n > r.words.length - r.i) fail("list length exceeds message");
  const items = []; for (let i = 0; i < n; i++) items.push(dec_topology_Face(r));
  return items.reduceRight((tail, head) => ({ $: "Con", head, tail }), { $: "Nil" });
}
// topology.bend:Solid
function enc_topology_Solid(v, out) {
  if (v?.$ !== "Solid") fail(`topology.bend:Solid constructor ${v?.$}`);
  enc_L_geometry_Vec3(v.vertices, out);
  enc_L_topology_Edge(v.edges, out);
  enc_L_topology_Face(v.faces, out);
}
function dec_topology_Solid(r) {
  return { $: "Solid", vertices: dec_L_geometry_Vec3(r), edges: dec_L_topology_Edge(r), faces: dec_L_topology_Face(r) };
}

export const codecs = {
  "topology.bend:Coedge": { key: "topology_Coedge",
    encode(value) { const out = []; enc_topology_Coedge(value, out); return Uint32Array.from(out); },
    decode(words) { const r = reader(words), value = dec_topology_Coedge(r); if (r.i !== words.length) fail("trailing words"); return value; },
  },
  "topology.bend:Edge": { key: "topology_Edge",
    encode(value) { const out = []; enc_topology_Edge(value, out); return Uint32Array.from(out); },
    decode(words) { const r = reader(words), value = dec_topology_Edge(r); if (r.i !== words.length) fail("trailing words"); return value; },
  },
  "topology.bend:Face": { key: "topology_Face",
    encode(value) { const out = []; enc_topology_Face(value, out); return Uint32Array.from(out); },
    decode(words) { const r = reader(words), value = dec_topology_Face(r); if (r.i !== words.length) fail("trailing words"); return value; },
  },
  "topology.bend:Solid": { key: "topology_Solid",
    encode(value) { const out = []; enc_topology_Solid(value, out); return Uint32Array.from(out); },
    decode(words) { const r = reader(words), value = dec_topology_Solid(r); if (r.i !== words.length) fail("trailing words"); return value; },
  },
};

export const ops = [
];
