// Resumable corpus runner: every unique modeling file of ~/Workspace/cad
// (FeatureScript and build123d) through the production CLIs on the default JS
// path. Results are appended to out/corpus/runs.jsonl, one JSON line per unit.
//
//   node scripts/corpus/targets.mjs            # once: build out/corpus/targets.json
//   node scripts/corpus/run.mjs [options]
//
// Options:
//   --phase 0|1|2|all      0 = anchor (frozen r10b fixture), 1 = family representatives,
//                          2 = remaining unique files (default all)
//   --concurrency N        at most 3 (shared machine); default 3
//   --limit N              stop after N new units
//   --only <substring>     only units whose key contains the substring
//   --keys-file <path>     only units whose key is listed (one per line)
//   --retry-timeouts       re-run units whose latest record is a timeout, with 2.5x the budget (max 900 s)
//   --rerun                ignore existing records for the selected units
//   --label <name>         standing benchmark: write to out/corpus/bench/<name>/{runs,run-meta}.jsonl
//                          (and tmp/corpus/bench/<name>/out) instead of the baseline files
//   --cluster <key>        only units whose BASELINE record failed in this cluster
//                          (keys as in out/corpus/summary.json, e.g. fs-missing-builtin)
//   --skip-fragments       skip the header-less include fragments (out/corpus/fragments.json)
//   --no-store-manifests   do not pass store manifests (the pre-W4 behavior, for A/B runs)
//
// Benchmark workflow (docs/corpus/README.md): run with --label, then
//   node scripts/corpus/summarize.mjs --label <name>
//   node scripts/corpus/compare.mjs --label <name>
//
// Invocation per unit (recorded verbatim in each record):
//   FS: node bin/wonky.mjs <corpus file> --format step --out tmp/corpus/out/<slug>/model [--feature <name>]
//         [--modules var/onshape-store/manifests/<corpus path>.json]
//       run in place (read only; the CLI reads the file and an optional sibling
//       modules.json, and writes only to --out). Default modeling policy (strict).
//       Frozen Onshape inputs (docs/onshape-inputs.md): a sibling modules.json
//       wins, as in the CLI; otherwise the store manifest generated by
//       scripts/snapshot-modules.mjs for this corpus file is passed with
//       --modules when it exists. Files with neither run exactly as before.
//       The record's `modules` field names the manifest used and its SHA-256.
//   Py: node bin/wonky-python.mjs <mirror file> --python tmp/corpus/uv-python
//       --timeout-ms <budget-15s> --out tmp/corpus/out/<slug>/model, cwd tmp/corpus/work/<slug>.
//       The mirror (tmp/corpus/src) holds copies of the corpus .py and small text
//       data files, so model code that writes next to itself cannot touch the
//       read-only corpus. tmp/corpus/uv-python is `exec uv run --no-project --quiet python "$@"`.
// Failures are re-run once through scripts/corpus/probe.mjs (same production
// entrypoints and options) to get the error class, failing modeling call and
// call chain, which the CLI output does not include.
import { spawn, execSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync, statSync, copyFileSync, readdirSync, rmSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { loadavg } from 'node:os';
import { REPO, CORPUS_ROOT, OUT_DIR, TMP_DIR, classify, messagePattern, runPaths } from './lib.mjs';
import { loadRecords } from './clusters.mjs';

const RUNNER = 'corpus-run/1';
const args = process.argv.slice(2);
const opt = (name, fallback) => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : fallback; };
const phase = opt('--phase', 'all');
const concurrency = Math.min(3, Number(opt('--concurrency', 3)));
const limit = Number(opt('--limit', Infinity));
const only = opt('--only', null);
const keysFile = opt('--keys-file', null);
const keySet = keysFile ? new Set(readFileSync(keysFile, 'utf8').split('\n').map(s => s.trim()).filter(Boolean)) : null;
const retryTimeouts = args.includes('--retry-timeouts');
const rerun = args.includes('--rerun');
const label = opt('--label', null);
const clusterFilter = opt('--cluster', null);
const skipFragments = args.includes('--skip-fragments');
const useStoreManifests = !args.includes('--no-store-manifests');
const { dir: RUN_DIR, runs: RUNS, meta: META } = runPaths(label);
const OUT_ROOT = label ? join(TMP_DIR, 'bench', label, 'out') : join(TMP_DIR, 'out');

const targets = JSON.parse(readFileSync(join(OUT_DIR, 'targets.json'), 'utf8'));
mkdirSync(OUT_DIR, { recursive: true });
mkdirSync(RUN_DIR, { recursive: true });

// ---------------------------------------------------------------- environment
const PY_WRAPPER = join(TMP_DIR, 'uv-python');
if (!existsSync(PY_WRAPPER)) {
  mkdirSync(TMP_DIR, { recursive: true });
  writeFileSync(PY_WRAPPER, '#!/bin/sh\nexec uv run --no-project --quiet python "$@"\n');
  chmodSync(PY_WRAPPER, 0o755);
}
const MIRROR = join(TMP_DIR, 'src');
const MIRROR_EXT = /\.(py|json|toml|ya?ml|csv|txt|fs|svg|dxf|cfg|ini)$/i;
const SKIP = new Set(['node_modules', 'vendor', 'site-packages', '__pycache__', 'venv', 'dist-packages']);
function mirrorProject(project) {
  const stamp = join(MIRROR, `.${project}.mirrored`);
  if (existsSync(stamp)) return;
  let files = 0;
  const visit = dir => {
    let entries; try { entries = readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const e of entries) {
      if (e.name.startsWith('.')) continue;
      const p = join(dir, e.name);
      if (e.isDirectory()) { if (!SKIP.has(e.name)) visit(p); continue; }
      if (!e.isFile() || !MIRROR_EXT.test(e.name)) continue;
      if (statSync(p).size > 1 << 20) continue;
      const target = join(MIRROR, relative(CORPUS_ROOT, p));
      mkdirSync(dirname(target), { recursive: true });
      copyFileSync(p, target); files++;
    }
  };
  visit(join(CORPUS_ROOT, project));
  mkdirSync(MIRROR, { recursive: true });
  writeFileSync(stamp, JSON.stringify({ project, files, at: new Date().toISOString() }));
}

const uptime = () => { try { return execSync('uptime', { encoding: 'utf8' }).trim(); } catch { return null; } };
let pythonVersion = null;
try { pythonVersion = execSync(`${PY_WRAPPER} -I -S -c "import sys; print(sys.version.split()[0])"`, { encoding: 'utf8' }).trim(); } catch {}
const nodeVersion = process.version;
const gitHead = (() => { try { return execSync('git rev-parse HEAD', { cwd: REPO, encoding: 'utf8' }).trim(); } catch { return null; } })();
const session = new Date().toISOString();
const meta = row => appendFileSync(META, JSON.stringify({ session, at: new Date().toISOString(), ...row }) + '\n');
meta({ event: 'start', runner: RUNNER, args, label, concurrency, storeManifests: useStoreManifests, uptime: uptime(), loadavg: loadavg(), node: nodeVersion, python: pythonVersion,
  gitHead, backend: process.env.WONKY_BACKEND ?? 'default (js)' });
if (process.env.WONKY_BACKEND) throw new Error('WONKY_BACKEND is set; corpus runs must use the default JS path');

// ---------------------------------------------------------------- selection
const latest = new Map();
if (existsSync(RUNS)) for (const line of readFileSync(RUNS, 'utf8').split('\n')) {
  if (!line.trim()) continue;
  try { const r = JSON.parse(line); if (r.runner === RUNNER) latest.set(r.key, r); } catch {}
}
let queue = targets.units.filter(u => (phase === 'all' || String(u.phase) === phase) && (!only || u.key.includes(only)) && (!keySet || keySet.has(u.key)));
if (clusterFilter) {
  const inCluster = new Set(loadRecords().recs.filter(r => r.cluster === clusterFilter).map(r => r.key));
  if (!inCluster.size) throw new Error(`No baseline unit failed in cluster '${clusterFilter}'`);
  queue = queue.filter(u => inCluster.has(u.key));
}
if (skipFragments) {
  const fragments = new Set(JSON.parse(readFileSync(join(OUT_DIR, 'fragments.json'), 'utf8')).rows.map(r => r.path));
  queue = queue.filter(u => !fragments.has(u.path));
}
if (retryTimeouts) {
  queue = queue.filter(u => latest.get(u.key)?.status === 'timeout')
    .map(u => ({ ...u, timeoutS: Math.min(900, Math.round((latest.get(u.key).timeoutS ?? u.timeoutS) * 2.5)) }));
} else if (!rerun) queue = queue.filter(u => !latest.has(u.key));
queue = queue.slice(0, limit);
console.error(`[corpus] ${queue.length} units to run (phase ${phase}, concurrency ${concurrency}); ${latest.size} already recorded`);

// ---------------------------------------------------------------- execution
const childEnv = { ...process.env }; delete childEnv.WONKY_BACKEND;
const slug = u => u.key.replace(/[^A-Za-z0-9._-]+/g, '_').slice(-150);

// Frozen Onshape inputs for an FS unit: the sibling modules.json the CLI picks
// up by itself, else the store manifest for this corpus path (passed with
// --modules), else none. The anchor (u.abs) keeps its fixture manifest.
const STORE_MANIFESTS = join(REPO, 'var/onshape-store/manifests');
const sha256File = p => createHash('sha256').update(readFileSync(p)).digest('hex');
function moduleInputs(u, file) {
  const sibling = join(dirname(file), 'modules.json');
  if (existsSync(sibling)) return { source: 'sibling', path: sibling, pass: false };
  if (!useStoreManifests || u.abs) return null;
  const manifest = join(STORE_MANIFESTS, `${u.path}.json`);
  return existsSync(manifest) ? { source: 'store', path: manifest, pass: true } : null;
}
function exec(argv, { cwd, timeoutS }) {
  return new Promise(resolve => {
    const t0 = performance.now();
    const child = spawn(argv[0], argv.slice(1), { cwd, detached: true, stdio: ['ignore', 'pipe', 'pipe'], env: childEnv });
    let stdout = '', stderr = '', timedOut = false;
    child.stdout.on('data', d => { stdout += d; if (stdout.length > 4e6) stdout = stdout.slice(-2e6); });
    child.stderr.on('data', d => { stderr += d; if (stderr.length > 4e6) stderr = stderr.slice(-2e6); });
    const timer = setTimeout(() => { timedOut = true; try { process.kill(-child.pid, 'SIGKILL'); } catch {} }, timeoutS * 1000);
    child.on('close', (code, signal) => {
      clearTimeout(timer);
      try { process.kill(-child.pid, 'SIGKILL'); } catch {}
      resolve({ code, signal, stdout, stderr, timedOut, wallMs: Math.round(performance.now() - t0) });
    });
    child.on('error', e => { clearTimeout(timer); resolve({ code: -1, signal: null, stdout, stderr: String(e), timedOut, wallMs: Math.round(performance.now() - t0) }); });
  });
}

const BODY_LINE = /^(\S+): (\d+) vertices · (\d+) edges · (\d+) faces · (.+?) · closed topology$/;
function successStats(prefix) {
  const brep = `${prefix}.brep.json`;
  if (!existsSync(brep)) return null;
  const model = JSON.parse(readFileSync(brep, 'utf8'));
  const bodies = model.bodies.map(b => ({
    id: b.id, vertices: b.validation?.vertices, edges: b.validation?.edges, faces: b.validation?.faces,
    volumeMm3: b.validation?.volumeMm3 ?? null, boundsMm: b.validation?.boundsMm ?? null,
    closed: b.validation?.closed ?? null, name: b.name ?? null,
  }));
  const min = [Infinity, Infinity, Infinity], max = [-Infinity, -Infinity, -Infinity];
  for (const b of bodies) if (b.boundsMm) for (let i = 0; i < 3; i++) { min[i] = Math.min(min[i], b.boundsMm.min[i]); max[i] = Math.max(max[i], b.boundsMm.max[i]); }
  const volumes = bodies.map(b => b.volumeMm3);
  return {
    bodies, backend: model.backend ?? null, feature: model.source?.feature ?? null,
    totals: {
      bodies: bodies.length, faces: bodies.reduce((s, b) => s + (b.faces ?? 0), 0), edges: bodies.reduce((s, b) => s + (b.edges ?? 0), 0),
      volumeMm3: volumes.every(v => typeof v === 'number') ? volumes.reduce((s, v) => s + v, 0) : null,
      volumeComplete: volumes.every(v => typeof v === 'number'),
      bboxMm: Number.isFinite(min[0]) ? { min, max } : null,
    },
    step: existsSync(`${prefix}.step`) ? `${prefix}.step` : null,
  };
}

// "path:line:col: message" (FS), "path:line: message" (Py), "wonky: message"
function parseCliError(stderr, file) {
  const lines = stderr.trim().split('\n').filter(Boolean);
  const exportRefusals = lines.filter(l => /^wonky: no \.\S+ written:/.test(l));
  let last = lines.filter(l => !/^wonky: no \.\S+ written:/.test(l)).at(-1) ?? exportRefusals.at(-1) ?? '';
  if (!last && exportRefusals.length) last = exportRefusals[0];
  const esc = file.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  let m = last.match(new RegExp(`^${esc}:(\\d+):(\\d+): ([\\s\\S]*)$`));
  if (m) return { line: +m[1], column: +m[2], message: m[3], exportRefusals };
  m = last.match(new RegExp(`^${esc}:(\\d+): ([\\s\\S]*)$`));
  if (m) return { line: +m[1], column: null, message: m[2], exportRefusals };
  m = last.match(new RegExp(`^${esc}: ([\\s\\S]*)$`));
  if (m) return { line: null, column: null, message: m[1], exportRefusals };
  m = last.match(/^wonky(?:-python)?: ([\s\S]*)$/);
  if (m) return { line: null, column: null, message: m[1], exportRefusals };
  return { line: null, column: null, message: last.slice(0, 2000), exportRefusals };
}

async function runUnit(u) {
  const s = slug(u);
  const outPrefix = join(OUT_ROOT, s, 'model');
  rmSync(dirname(outPrefix), { recursive: true, force: true });
  mkdirSync(dirname(outPrefix), { recursive: true });
  let file, argv, cwd, modules = null;
  if (u.frontend === 'fs') {
    file = u.abs ?? join(CORPUS_ROOT, u.path);
    modules = moduleInputs(u, file);
    argv = [process.execPath, 'bin/wonky.mjs', file, '--format', 'step', '--out', outPrefix, ...(u.feature ? ['--feature', u.feature] : []),
      ...(modules?.pass ? ['--modules', modules.path] : [])];
    cwd = REPO;
  } else {
    mirrorProject(u.project);
    if (u.path.includes('/') && !existsSync(join(MIRROR, u.path))) mirrorProject(u.path.split('/')[0]);
    file = join(MIRROR, u.path);
    cwd = join(TMP_DIR, 'work', s);
    mkdirSync(cwd, { recursive: true });
    argv = [process.execPath, join(REPO, 'bin/wonky-python.mjs'), file, '--python', PY_WRAPPER,
      '--timeout-ms', String(Math.max(10000, (u.timeoutS - 15) * 1000)), '--out', outPrefix];
  }
  const startedAt = new Date().toISOString(), load = loadavg();
  const r = await exec(argv, { cwd, timeoutS: u.timeoutS });
  const record = {
    runner: RUNNER, session, key: u.key, order: u.order, phase: u.phase, frontend: u.frontend, project: u.project,
    family: u.family, representative: u.representative, path: u.path, sha: u.sha, lines: u.lines, feature: u.feature,
    invocation: { argv: argv.map(a => a.replace(REPO + '/', '')).map((a, i) => (i === 0 ? 'node' : a)), cwd: relative(REPO, cwd) || '.' },
    modules: modules ? { source: modules.source, path: relative(REPO, modules.path), sha256: sha256File(modules.path) } : undefined,
    timeoutS: u.timeoutS, startedAt, loadavgAtStart: load.map(x => +x.toFixed(2)), wallMs: r.wallMs, exitCode: r.code, signal: r.signal,
  };
  const bodyLines = r.stdout.split('\n').map(l => l.match(BODY_LINE)).filter(Boolean)
    .map(m => ({ id: m[1], vertices: +m[2], edges: +m[3], faces: +m[4], volume: m[5] }));
  if (r.timedOut) {
    Object.assign(record, { status: 'timeout', kind: 'runner-timeout', message: `No result within ${u.timeoutS} s`, cliBodyLines: bodyLines.length });
  } else if (r.code === 0) {
    const stats = successStats(outPrefix);
    if (!stats) Object.assign(record, { status: 'crash', kind: 'missing-output', message: 'Exit 0 without brep.json' });
    else Object.assign(record, { status: 'ok', kind: 'ok', cliBodyLines: bodyLines, ...stats });
  } else {
    const e = parseCliError(r.stderr, file);
    Object.assign(record, { cliMessage: e.message, location: { file: u.path, line: e.line, column: e.column }, exportRefusals: e.exportRefusals.length ? e.exportRefusals : undefined });
    if (e.exportRefusals.length && bodyLines.length) {
      // The model built; an export format refused. Keep geometry stats.
      Object.assign(record, { cliBodyLines: bodyLines, ...(successStats(outPrefix) ?? {}) });
    }
    // Diagnostic probe through the same entrypoint for class + failing call.
    const probeArgv = u.frontend === 'fs'
      ? [process.execPath, 'scripts/corpus/probe.mjs', 'fs', file, ...(modules?.pass ? ['--modules', modules.path] : []), ...(u.feature ? [u.feature] : [])]
      : [process.execPath, join(REPO, 'scripts/corpus/probe.mjs'), 'py', file, PY_WRAPPER, String(Math.max(10000, (u.timeoutS - 15) * 1000))];
    let probe = null;
    if (!e.exportRefusals.length || !bodyLines.length) {
      const p = await exec(probeArgv, { cwd, timeoutS: u.timeoutS });
      const line = p.stdout.trim().split('\n').filter(l => l.startsWith('{')).at(-1);
      try { probe = line ? JSON.parse(line) : { ok: null, note: p.timedOut ? 'probe timeout' : `probe produced no JSON (exit ${p.code})`, stderrTail: p.stderr.slice(-800) }; }
      catch { probe = { ok: null, note: 'probe JSON parse failed' }; }
      probe.wallMs = p.wallMs;
    }
    const signalCrash = r.signal || /FATAL ERROR|heap out of memory|Segmentation fault|Abort trap/.test(r.stderr);
    const cls = e.exportRefusals.length && bodyLines.length
      ? { status: 'capability', kind: 'export-refused' }
      : signalCrash ? { status: 'crash', kind: r.signal ? `signal-${r.signal}` : 'runtime-abort' }
      : classify({ errorClass: probe?.errorClass, message: e.message, userThrow: probe?.userThrow, completedOperations: probe?.trace?.completed });
    Object.assign(record, cls, {
      errorClass: probe?.errorClass ?? null,
      message: e.message,
      pattern: messagePattern(e.message),
      failingOperation: probe?.trace?.failedOperation ?? null,
      completedOperations: probe?.trace?.completed ?? null,
      lastCompletedOperation: probe?.trace?.lastCompleted ?? null,
      sourceLine: probe?.sourceLine ?? null,
      userThrow: probe?.userThrow ?? null,
      traceback: probe?.traceback ?? null,
      jsStack: cls.status === 'crash' || cls.kind === 'kernel' ? probe?.jsStack : undefined,
      probe: probe ? { ok: probe.ok, wallMs: probe.wallMs, note: probe.note, messageMatches: probe.message ? probe.message === e.message || e.message.endsWith(probe.message) || probe.message.endsWith(e.message) : null } : null,
      stderrTail: r.stderr.slice(-1500),
    });
  }
  appendFileSync(RUNS, JSON.stringify(record) + '\n');
  // Keep the STEP of successes for the reference comparison; drop big B-rep JSON otherwise.
  if (record.status !== 'ok') rmSync(dirname(outPrefix), { recursive: true, force: true });
  return record;
}

let done = 0;
const counts = {};
async function worker() {
  while (queue.length) {
    const u = queue.shift();
    let rec;
    try { rec = await runUnit(u); }
    catch (error) {
      rec = { runner: RUNNER, session, key: u.key, frontend: u.frontend, path: u.path, family: u.family, project: u.project, status: 'crash', kind: 'runner-error', message: String(error.stack ?? error).slice(0, 2000) };
      appendFileSync(RUNS, JSON.stringify(rec) + '\n');
    }
    done++; counts[rec.status] = (counts[rec.status] ?? 0) + 1;
    console.error(`[${done}] ${rec.status.padEnd(10)} ${String(rec.wallMs ?? '').padStart(7)}ms ${u.key} ${rec.status === 'ok' ? `bodies=${rec.totals?.bodies}` : (rec.message ?? '').slice(0, 140)}`);
    if (done % 25 === 0) meta({ event: 'progress', done, counts, uptime: uptime(), loadavg: loadavg() });
  }
}
await Promise.all(Array.from({ length: concurrency }, worker));
meta({ event: 'end', done, counts, uptime: uptime(), loadavg: loadavg() });
console.error(`[corpus] done ${done}: ${JSON.stringify(counts)}`);
