FeatureScript 3044;
import(path : "onshape/std/common.fs", version : "3044.0");
// R20 kernel test case kt6_coplanar_union: KT6 coplanar union. Generated by kernel-cases/make_cases.py.

// ---- case helpers (mm numbers in, unit values out) ----
function ktPlane(origin is Vector, normal is Vector, xDirection is Vector) returns Plane
{
    return plane(origin * millimeter, normal, xDirection);
}

// Closed polygon of 2D points (mm) on sketchPlane, extruded along its normal by depth (mm).
function ktPrism(context is Context, id is Id, sketchPlane is Plane, points is array, depth is number) returns Query
{
    var sketch = newSketchOnPlane(context, id + "sketch", { "sketchPlane" : sketchPlane });
    for (var i = 0; i < size(points); i += 1)
    {
        const j = (i + 1) % size(points);
        skLineSegment(sketch, "s" ~ i, { "start" : points[i] * millimeter, "end" : points[j] * millimeter });
    }
    skSolve(sketch);
    opExtrude(context, id + "extrude", { "entities" : qSketchRegion(id + "sketch", false),
        "direction" : sketchPlane.normal, "endBound" : BoundingType.BLIND, "endDepth" : depth * millimeter });
    opDeleteBodies(context, id + "clean", { "entities" : qCreatedBy(id + "sketch", EntityType.BODY) });
    return qCreatedBy(id + "extrude", EntityType.BODY);
}

// Axis-aligned block from lo to hi (mm).
function ktBlock(context is Context, id is Id, lo is Vector, hi is Vector) returns Query
{
    const base = ktPlane(vector(0, 0, lo[2]), vector(0, 0, 1), vector(1, 0, 0));
    return ktPrism(context, id, base,
        [vector(lo[0], lo[1]), vector(hi[0], lo[1]), vector(hi[0], hi[1]), vector(lo[0], hi[1])], hi[2] - lo[2]);
}

// Cylinder of radius r (mm) from origin along unit axis over length (mm).
function ktCylinder(context is Context, id is Id, origin is Vector, axis is Vector, r is number, length is number) returns Query
{
    const xDirection = abs(axis[2]) > 0.9 ? vector(1, 0, 0) : vector(0, 0, 1);
    var sketch = newSketchOnPlane(context, id + "sketch", { "sketchPlane" : ktPlane(origin, axis, cross(axis, cross(xDirection, axis))) });
    skCircle(sketch, "c", { "center" : vector(0, 0) * millimeter, "radius" : r * millimeter });
    skSolve(sketch);
    opExtrude(context, id + "extrude", { "entities" : qSketchRegion(id + "sketch", false),
        "direction" : axis, "endBound" : BoundingType.BLIND, "endDepth" : length * millimeter });
    opDeleteBodies(context, id + "clean", { "entities" : qCreatedBy(id + "sketch", EntityType.BODY) });
    return qCreatedBy(id + "extrude", EntityType.BODY);
}

function ktSubtract(context is Context, id is Id, target is Query, tools is Query) returns Query
{
    opBoolean(context, id, { "targets" : target, "tools" : tools, "operationType" : BooleanOperationType.SUBTRACTION });
    return target;
}

// Exactly one solid body, else a loud regeneration error.
function ktOne(context is Context, q is Query, what is string) returns Query
{
    const n = size(evaluateQuery(context, q));
    if (n != 1)
        throw regenError("kernel case " ~ what ~ ": expected 1 body, got " ~ n);
    return q;
}

function ktName(context is Context, q is Query, name is string) returns Query
{
    setProperty(context, { "entities" : q, "propertyType" : PropertyType.NAME, "value" : name });
    return q;
}

// KT6: union of four blocks with coplanar faces and 0.5 mm overlaps (the R20 rule against
// BOOLEAN_NON_MANIFOLD at touching primitives):
//  A (0,0,0)-(20,20,10); B overlaps A by 0.5 in x, same top/bottom/side planes;
//  C overlaps B at a corner by 0.5 in x and y, same top/bottom; D sits on A with 0.5 overlap in z,
//  flush with A at x = 0 and y = 0.
annotation { "Feature Type Name" : "KT6 coplanar union" }
export const kt6CoplanarUnion = defineFeature(function(context is Context, id is Id, definition is map)
    precondition {}
    {
        const a = ktBlock(context, id + "a", vector(0, 0, 0), vector(20, 20, 10));
        const b = ktBlock(context, id + "b", vector(19.5, 0, 0), vector(40, 20, 10));
        const c = ktBlock(context, id + "c", vector(39.5, 19.5, 0), vector(50, 30, 10));
        const d = ktBlock(context, id + "d", vector(0, 0, 9.5), vector(10, 10, 15));
        opBoolean(context, id + "union", { "tools" : qUnion([a, b, c, d]), "operationType" : BooleanOperationType.UNION });
        const body = ktOne(context, qUnion([a, b, c, d]), "coplanar union");
        ktName(context, body, "KT6 coplanar union 0p5 overlap");
    });
