//! Exact quadratic-root predicates for AR1, SI1/SI2, TC1 and BL1.
//!
//! Authoritative inputs are the binary64 words at this boundary (E9), not a
//! rounded construction of an intersection. Intersections retain expansion
//! numerators, positive denominators and discriminants. No atan2, normalization,
//! snapping or modeling tolerance participates in ordering.
//!
//! Scope: rational polynomials and fields generated by at most two *square*
//! roots. Two independent square roots can have algebraic degree FOUR: N2's
//! "degree 2" denotes the root equations, not a claim of minimal degree <= 2.
//! No arbitrary higher-degree roots, three-root fields or geometry operations.
//! See `census.csv` for consumers and expressions delegated to N3/AL2.
//!
//! Inputs obey wonky-num's range policy. Expansion overflow or a product below
//! its error-free window returns `Numeric(NotExact)`; full exponent-range
//! completeness is not claimed. Intersections/points are predicate operands,
//! not approximate geometry or B-rep operations.
//!
//! EX1 replay: set `N2_CERTIFICATES=/absolute/path.jsonl` on the `rational` test
//! to emit 200,000 actual scalar decisions. Names are `one_surd_sign` (a,b,c)
//! and `two_surd_sign` (a,b,c,d,e), canonical hex-f64, `claimed.Sign`. This is
//! sampled numeric replay, not global production tracing of geometry decisions.
#![deny(unused_must_use)]

mod exact;
mod filter;
mod geometry;

pub use geometry::{
    circle_circle, circle_line, compare_along_circle, compare_along_line, incircle,
    point_against_arc, Arc, ArcLocation, Circle, Intersections, Line, Point,
};
pub use wonky_num::Sign;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Refusal {
    Numeric(wonky_num::Refusal),
    NegativeRadicand,
    TooManyRadicands { supplied: usize, maximum: usize },
    InvalidGeometry(&'static str),
}
pub type Result<T> = std::result::Result<T, Refusal>;

pub(crate) fn check(xs: &[f64]) -> Result<()> {
    wonky_num::check_range(xs, "N2 input").map_err(|e| Refusal::Numeric(e.into_refusal()))
}

/// Sign of `a + b sqrt(c)`. The square root is the nonnegative real root.
pub fn sign_one(a: f64, b: f64, c: f64) -> Result<Sign> {
    sign_sum(a, &[(b, c)])
}

/// Sign of `a + b sqrt(c) + d sqrt(e)` with full sign cases before squaring.
pub fn sign_two(a: f64, b: f64, c: f64, d: f64, e: f64) -> Result<Sign> {
    sign_sum(a, &[(b, c), (d, e)])
}

/// Dynamic arity boundary: three terms are refused, never truncated, even when
/// a coefficient is zero or radicands happen to be equal. Callers choose N3.
pub fn sign_sum(a: f64, terms: &[(f64, f64)]) -> Result<Sign> {
    if terms.len() > 2 {
        return Err(Refusal::TooManyRadicands {
            supplied: terms.len(),
            maximum: 2,
        });
    }
    check(&[a])?;
    for &(b, c) in terms {
        check(&[b, c])?;
        if c < 0.0 {
            return Err(Refusal::NegativeRadicand);
        }
    }
    let mut approx = Some(filter::Ball::point(a));
    for &(b, c) in terms {
        approx =
            approx.and_then(|x| x.add(filter::Ball::point(c).sqrt()?.mul(filter::Ball::point(b))?));
    }
    if let Some(s) = approx.and_then(filter::sign) {
        return Ok(s);
    }
    let mut ctx = exact::Context::new();
    let (b, c) = terms.first().copied().unwrap_or((0.0, 0.0));
    let (d, e) = terms.get(1).copied().unwrap_or((0.0, 0.0));
    ctx.sign_field(
        &[exact::scalar(a), exact::scalar(b), exact::scalar(d), vec![]],
        &[exact::scalar(c), exact::scalar(e)],
    )
}
