// wonky (production) probe: how far does the PRODUCTION Python CLI get towards each
// fillet/chamfer call, and what does wonky's own B-rep look like right before it?
//
// For every build123d corpus file with a reachable 3D fillet/chamfer site:
//   1. copy the file's project (.py only) to tmp/fillet/wonky/src/ (the corpus is read only);
//   2. write a wrapper next to the copy that rebinds build123d.fillet/chamfer to a probe
//      and exec()s the unmodified model source. The probe counts calls; calls before the
//      K-th return the owner shape unchanged (the blend is OMITTED, which is recorded);
//      the K-th call prints the selected edges' wonky records (key = solid/index, curve,
//      endpoints, circle frame) and stops the model with the owner solid as `result`;
//   3. run `node bin/wonky-python.mjs <wrapper> --out <prefix>` (production CLI, default
//      JS backend) so wonky writes <prefix>.step / .brep.json of the owner.
// K = 1, 2, ... until the model no longer reaches a K-th call or fails first.
// The STEP is analysed afterwards by scripts/fillet/wonky_analyze.py (OCP measurement).
//
// Usage: node scripts/fillet/wonky-probe.mjs [--only substr] [--max-k 40] [--rerun]
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { spawnSync, spawn } from 'node:child_process';
import { dirname, join, basename } from 'node:path';

const REPO = new URL('../..', import.meta.url).pathname;
const CORPUS = '~/Workspace/cad';
const args = process.argv.slice(2);
const opt = k => (args.includes(k) ? args[args.indexOf(k) + 1] : null);
const only = opt('--only'), MAXK = Number(opt('--max-k') ?? 40), rerun = args.includes('--rerun');
const { sites } = JSON.parse(readFileSync(join(REPO, 'tmp/fillet/static.json'), 'utf8'));
const files = [...new Set(sites.filter(s => s.frontend === 'py' && s.reachable && s.dim === '3d').map(s => s.path))].filter(p => !only || p.includes(only));
const SRC = join(REPO, 'tmp/fillet/wonky/src'), OUT = join(REPO, 'tmp/fillet/wonky/out');
mkdirSync(OUT, { recursive: true });

function projectRoot(rel) {
  let d = dirname(join(CORPUS, rel));
  while (d.startsWith(CORPUS) && d !== CORPUS) { if (existsSync(join(d, 'pyproject.toml'))) return d; d = dirname(d); }
  return dirname(join(CORPUS, rel));
}
const copied = new Set();
function copyProject(root) {
  if (copied.has(root)) return;
  const dst = join(SRC, root.slice(CORPUS.length + 1)); mkdirSync(dst, { recursive: true });
  const r = spawnSync('rsync', ['-a', '--prune-empty-dirs', '--exclude=.venv', '--exclude=node_modules', '--exclude=__pycache__',
    '--include=*/', '--include=*.py', '--include=pyproject.toml', '--include=*.json', '--exclude=*', root + '/', dst + '/'], { encoding: 'utf8' });
  if (r.status !== 0) throw new Error(r.stderr);
  copied.add(root);
}

const wrapper = (modelPath, k) => `# fillet probe wrapper (generated by scripts/fillet/wonky-probe.mjs); K=${k}
import json as _json
import sys as _sys
import build123d as _b3d
import _b3d_core as _core

_K = ${k}
_MODEL = ${JSON.stringify(modelPath)}
_state = {"n": 0, "owner": None, "omitted": []}


class _ProbeStop(BaseException):
    pass


def _edges(objects):
    if isinstance(objects, (list, tuple)):
        out = []
        for o in objects:
            out.extend(_edges(o))
        return out
    return [objects]


def _probe(kind):
    def probe(objects, *args, **kwargs):
        _state["n"] += 1
        _f, _line = _sys._getframe(1), None
        while _f is not None:
            if _f.f_code.co_filename == _MODEL:
                _line = _f.f_lineno
                break
            _f = _f.f_back
        edges = _edges(objects)
        size = kwargs.get("radius", kwargs.get("length", args[0] if args else None))
        keyed = [e for e in edges if hasattr(e, "_key")]
        if not keyed:
            raise TypeError("fillet probe: objects are not wonky edges (%r)" % (type(edges[0]).__name__ if edges else None))
        owner = _core.Shape._from_handle(keyed[0]._key[0])
        if _state["n"] == _K:
            recs = []
            for e in keyed:
                r = dict(e._record)
                recs.append({"handle": e._key[0], "solid": e._key[1], "index": e._key[2], "record": r})
            print("FILLET_PROBE " + _json.dumps({"k": _K, "line": _line, "kind": kind, "size": size, "nEdges": len(edges),
                                                   "handles": sorted({e._key[0] for e in keyed}),
                                                   "omittedBefore": _state["omitted"], "edges": recs}, default=str))
            _state["owner"] = owner
            raise _ProbeStop()
        _state["omitted"].append({"k": _state["n"], "line": _line, "kind": kind, "size": size, "nEdges": len(edges)})
        return owner
    return probe


_b3d.fillet = _probe("fillet")
_b3d.chamfer = _probe("chamfer")
_g = {"__name__": "__main__", "__file__": _MODEL}
try:
    with open(_MODEL) as _fh:
        exec(compile(_fh.read(), _MODEL, "exec"), _g)
except _ProbeStop:
    pass
if _state["owner"] is None:
    print("FILLET_PROBE_END " + _json.dumps({"calls": _state["n"]}))
    result = _b3d.Box(1, 1, 1)
else:
    result = _state["owner"]
`;

function runOnce(model, k, prefix) {
  return new Promise(resolve => {
    const wrap = join(dirname(model), `__fillet_probe_k${k}.py`);
    writeFileSync(wrap, wrapper(model, k));
    const t0 = Date.now();
    const p = spawn('node', [join(REPO, 'bin/wonky-python.mjs'), wrap, '--python', join(REPO, 'tmp/corpus/uv-python'), '--timeout-ms', '240000', '--out', prefix], { cwd: dirname(model) });
    let out = '', err = '';
    p.stdout.on('data', d => { out += d; }); p.stderr.on('data', d => { err += d; });
    const timer = setTimeout(() => p.kill('SIGKILL'), 300000);
    p.on('close', code => { clearTimeout(timer); resolve({ code, out, err, wallS: (Date.now() - t0) / 1000 }); });
  });
}

const results = [];
const conc = 3; let idx = 0;
async function worker() {
  while (idx < files.length) {
    const rel = files[idx++];
    const slug = rel.replace(/[^A-Za-z0-9]+/g, '_');
    const outJson = join(OUT, slug + '.json');
    if (!rerun && existsSync(outJson)) { results.push(JSON.parse(readFileSync(outJson, 'utf8'))); continue; }
    const root = projectRoot(rel); copyProject(root);
    const model = join(SRC, rel);
    const rec = { path: rel, calls: [], stop: null };
    for (let k = 1; k <= MAXK; k++) {
      const prefix = join(OUT, slug, `k${k}`, 'model');
      mkdirSync(dirname(prefix), { recursive: true });
      const r = await runOnce(model, k, prefix);
      writeFileSync(join(OUT, slug, `k${k}`, 'log.txt'), r.out + '\n--- stderr ---\n' + r.err);
      const probe = r.out.split('\n').find(l => l.startsWith('FILLET_PROBE '));
      const end = r.out.split('\n').find(l => l.startsWith('FILLET_PROBE_END '));
      if (probe && r.code === 0) {
        const p = JSON.parse(probe.slice('FILLET_PROBE '.length));
        rec.calls.push({ ...p, step: existsSync(prefix + '.step') ? prefix + '.step' : null, wallS: r.wallS });
        continue;
      }
      if (end) { rec.stop = { k, kind: 'end', calls: JSON.parse(end.slice('FILLET_PROBE_END '.length)).calls, wallS: r.wallS }; break; }
      const msg = (r.err || r.out).trim().split('\n').filter(Boolean).slice(-3).join(' | ');
      rec.stop = { k, kind: probe ? 'probe-then-error' : 'error', exitCode: r.code, message: msg.slice(0, 600), wallS: r.wallS };
      break;
    }
    writeFileSync(outJson, JSON.stringify(rec, null, 1));
    results.push(rec);
    console.log(`${rel}: ${rec.calls.length} probed; stop ${rec.stop?.kind} ${rec.stop?.message?.slice(0, 160) ?? ''}`);
  }
}
await Promise.all(Array.from({ length: conc }, worker));
console.log('DONE', results.length);
