"""Eager build123d Algebra compatibility surface backed only by Bend.

Loaded by runner.py, never by an installed build123d or OpenCascade package.
Shape handles identify B-reps already constructed in the Node/Bend process.

This file is the loader. The implementation lives in private modules next to
it, loaded by path (files starting with "_" are not importable by models, and
frames in them count as shim frames for use-site locations):

- ``_b3d_core.py``: the host bridge, Shape, Box, Cylinder, Align, Mode,
  export_step/export_stl, and ``register_shape_method`` for Shape methods
  that other modules implement;
- ``_b3d_location.py``: Vector, Location, Rotation/Rot, Pos, Plane, Axis;
- further ``_b3d_*.py`` modules (sketch profiles, operations, queries) when
  present; a missing one is skipped, its names stay sentinels;
- ``_wonky_color.py``: Color.

Each module publishes ``BUILD123D = {name: object}`` (top-level names) and
optionally ``CLASS_ATTRIBUTES = {"Class.attribute": object}``; the core also
publishes ``SHIM_ATTRIBUTES`` (the bridge helpers the runner, _wonky_runtime
and cad_khana use as ``build123d._unsupported`` etc.).

The module binds every public name of build123d 0.13.0 (frozen with provenance
in build123d_names.json, generated by scripts/python/build123d-names.py).
A name is either implemented by those modules, bound to the very standard-library
object build123d re-exports (math.pi, typing.Any, pathlib.Path, ...), or bound
to a sentinel. A sentinel constructs nothing, so importing it or naming it in an
annotation succeeds; calling it, reading its attributes, isinstance()/
issubclass() against it, subclassing it or using it as a value raises a
capability error at that use site (line and column). Names that build123d
0.13.0 does not have, including enum members it lacks, raise
AttributeError/ImportError, as the real package does.
"""

import importlib as _importlib
import json as _json
import os as _os
import sys as _sys
import types as _types

# Set by the runner (python/runner.py) after loading; _b3d_core reads them here.
_channel = None
_source_filename = None
_SHIM_DIR = _os.path.dirname(_os.path.abspath(__file__))

with open(_os.path.join(_SHIM_DIR, "build123d_names.json"), encoding="utf-8") as _stream:
    _TABLE = _json.load(_stream)
del _stream

__version__ = _TABLE["provenance"]["version"]
# A package with no search path: build123d.<sub> resolves to the shim views
# registered below, or fails like a missing submodule, never to site-packages.
__path__ = []


def _load_private(module_name):
    """A wonky module next to the shim (python/<module>.py), loaded once by path, or None if absent.

    Loaded by path: the runner starts Python with -I, so this directory is not
    on sys.path, and names starting with "_" are not importable by models.
    """
    module = _sys.modules.get(module_name)
    if module is not None:
        return module
    path = _os.path.join(_SHIM_DIR, f"{module_name}.py")
    if not _os.path.isfile(path):
        return None
    from importlib import util as _util
    spec = _util.spec_from_file_location(module_name, path)
    module = _util.module_from_spec(spec)
    _sys.modules[module_name] = module
    try:
        spec.loader.exec_module(module)
    except BaseException:
        del _sys.modules[module_name]
        raise
    return module


# Implementation modules in dependency order; the core is required.
_MODULES = ("_b3d_core", "_b3d_location", "_b3d_sketch", "_b3d_ops", "_b3d_query", "_b3d_blend")
_CLASS_ATTRIBUTES = {}
for _module_name in _MODULES:
    _module = _load_private(_module_name)
    if _module is None:
        if _module_name == "_b3d_core":
            raise ImportError("the Bend build123d shim needs python/_b3d_core.py")
        continue
    globals().update(getattr(_module, "SHIM_ATTRIBUTES", {}))
    for _name, _value in getattr(_module, "BUILD123D", {}).items():
        if _name not in _TABLE["names"]:
            raise RuntimeError(f"{_module_name} implements {_name!r}, which is not a build123d {__version__} name")
        globals()[_name] = _value
    _CLASS_ATTRIBUTES.update(getattr(_module, "CLASS_ATTRIBUTES", {}))
del _module_name, _module

# build123d.Color: a value object without geometry (khana package, python/_wonky_color.py).
# Without that module, the name table below binds a use-site sentinel instead.
_color = _load_private("_wonky_color")
if _color is not None:
    Color = _color.Color
del _color


# ---------------------------------------------------------------------------
# The complete build123d 0.13.0 name table.

_READER_MODULES = ("build123d.importers", "build123d.import_dxf")

# build123d operations that no shim module can build because the Bend kernel
# lacks the operation itself. Each note names that missing kernel operation and
# is appended to the capability message, so a stop at one of these names reads
# as kernel demand, not as a missing shim binding (docs/python-frontend.md).
# Solid-edge fillet and chamfer are python/_b3d_blend.py (the Bend fillet); 2D
# vertex blends of sketch profiles are not.
_GAP_FILLET = "Bend has no 2D vertex fillet of sketch profiles (it blends solid edges only)"
_GAP_CHAMFER = "Bend has no 2D vertex chamfer of sketch profiles (it blends solid edges only)"
_GAP_TEXT = "Bend has no font outlines (no font loading and no glyph outline curves)"
_GAP_OFFSET = "Bend has no offset operation (offset of 2D wires and faces, or of solid surfaces)"
_GAP_MIRROR = ("Bend has no reflection transform (its rigid transform accepts only rotations with "
               "determinant +1)")
_GAP_LOFT = ("Bend has no general loft: its only loft is the exact frustum between two coaxial circles (Cone); "
             "other sections need ruled or skinned surfaces")
_GAP_SWEEP = "Bend has no sweep along a path (it builds only straight extrusions and revolutions)"
_GAP_SPLINE = "Bend has no B-spline curves (its curves are lines, circles and ellipses)"
_GAP_SECTION = ("Bend computes solid/plane section contours (kernel/section.bend) but has no operation that "
                "builds the planar section faces build123d's section() returns")
_GAP_SVG = ("Bend has no 2D drawing export (projection of edges to a view plane with hidden-line removal); "
            "wonky exports STEP and STL")
_GAP_TORUS = "Bend has no torus surface (its surfaces are planes, cylinders and cones)"
_GAP_SPHERE = "Bend has no sphere surface (its surfaces are planes, cylinders and cones)"

# Keyed by the build123d 0.13.0 name: a top-level name, or "Class.attribute"
# for the methods that are the same operation (each one exists on that class in
# build123d 0.13.0; "Shape" is the shim's Shape, which also stands for Part and
# Compound results). On a sentinel class the note is appended by
# _Unimplemented.__getattr__; on an implemented class _install_kernel_gaps
# binds a descriptor that fails at the attribute's use site.
_KERNEL_GAPS = {
    "Text": _GAP_TEXT, "offset": _GAP_OFFSET,
    "mirror": _GAP_MIRROR, "loft": _GAP_LOFT, "sweep": _GAP_SWEEP, "Spline": _GAP_SPLINE,
    "section": _GAP_SECTION, "ExportSVG": _GAP_SVG, "Torus": _GAP_TORUS, "Sphere": _GAP_SPHERE,
    "Edge.make_spline": _GAP_SPLINE,
    "Solid.make_sphere": _GAP_SPHERE, "Solid.make_torus": _GAP_TORUS, "Solid.make_loft": _GAP_LOFT,
    "Solid.sweep": _GAP_SWEEP, "Face.sweep": _GAP_SWEEP, "Compound.make_text": _GAP_TEXT,
    "Wire.offset_2d": _GAP_OFFSET, "Edge.offset_2d": _GAP_OFFSET,
    "Location.mirror": _GAP_MIRROR,
}
for _owner in ("Shape", "Part", "Compound", "Solid", "Sketch"):
    _KERNEL_GAPS.update({f"{_owner}.mirror": _GAP_MIRROR, f"{_owner}.offset_3d": _GAP_OFFSET})
_KERNEL_GAPS.update({"Sketch.fillet": _GAP_FILLET, "Sketch.chamfer": _GAP_CHAMFER})
for _owner in ("Face", "Wire", "Edge"):
    _KERNEL_GAPS[f"{_owner}.mirror"] = _GAP_MIRROR
del _owner


def _note(name, entry):
    """Why a sentinel is one, appended to its capability message."""
    if name in _KERNEL_GAPS:
        return f"; {_KERNEL_GAPS[name]}"
    module = entry.get("module") or ""
    if name.startswith("import_") and module in _READER_MODULES:
        # Decision 3 (docs/python-khana.md): external geometry files are not model inputs.
        return ("; it reads external geometry from a file, and the wonky package policy excludes external "
                "geometry: production geometry must be constructed in Bend (docs/python-khana.md)")
    if entry["origin"] == "ocp":
        return ("; it is an OpenCascade (OCP) name re-exported by build123d, and external geometry is disabled: "
                "production geometry must be constructed in Bend")
    if entry["origin"] != "reexport":
        return ""
    if module.split(".")[0] in _sys.stdlib_module_names:
        return f"; build123d re-exports it from '{module}', the Bend shim does not"
    return (f"; build123d re-exports it from the third-party package '{module.split('.')[0]}', "
            f"which wonky does not provide")


def _stdlib(source):
    """The standard-library object that build123d re-exports, or None if this Python lacks it.

    The table records only verified identities (scripts/python/build123d-names.py).
    A private home module of a newer Python (pathlib._local) falls back to its
    public parent (pathlib).
    """
    module_name, attribute = source
    parts = module_name.split(".")
    for depth in range(len(parts), 0, -1):
        try:
            module = _importlib.import_module(".".join(parts[:depth]))
        except ImportError:
            continue
        if attribute is None:
            return module if depth == len(parts) else None
        if hasattr(module, attribute):
            return getattr(module, attribute)
    return None


class _Unimplemented(type):
    """Metaclass of use-site capability sentinels for build123d names without a Bend implementation.

    A sentinel may be imported, compared by identity, subscripted as a type and
    used in annotations (``-> Sketch``, ``Part | None``, ``ShapeList[Edge]``).
    Everything that would need the real object raises the capability error
    where it happens.
    """

    def __new__(mcls, name, bases, namespace, **kwargs):
        if kwargs.pop("_wonky_sentinel", False):
            return super().__new__(mcls, name, bases, namespace)
        base = next(b for b in bases if isinstance(b, _Unimplemented))
        return base._wonky_fail(f"Subclassing {base._wonky_name}")

    def __init__(cls, name, bases, namespace, **kwargs):
        super().__init__(name, bases, namespace)

    def _wonky_fail(cls, what):
        return _unsupported(f"{what} is not implemented by the Python frontend{cls._wonky_note}")

    def __call__(cls, *args, **kwargs):
        return cls._wonky_fail(cls._wonky_name)

    def __getattr__(cls, name):
        if name.startswith("_"):
            raise AttributeError(name)
        gap = _KERNEL_GAPS.get(f"{cls._wonky_name.rsplit('.', 1)[-1]}.{name}")
        if gap is not None:  # e.g. Edge.make_spline: the note of the operation, not of the class
            return _unsupported(f"{cls._wonky_name}.{name} is not implemented by the Python frontend; {gap}")
        return cls._wonky_fail(f"{cls._wonky_name}.{name}")

    def __setattr__(cls, name, value):
        if name.startswith("_"):
            return super().__setattr__(name, value)
        return cls._wonky_fail(f"Assigning {cls._wonky_name}.{name}")

    def __instancecheck__(cls, instance):
        return cls._wonky_fail(f"isinstance() against {cls._wonky_name}")

    def __subclasscheck__(cls, subclass):
        return cls._wonky_fail(f"issubclass() against {cls._wonky_name}")

    def __getitem__(cls, item):
        if cls._wonky_kind in ("class", "alias"):
            return cls  # a parametrized type in an annotation builds nothing
        return cls._wonky_fail(f"{cls._wonky_name}[...]")

    def __repr__(cls):
        return f"<{cls._wonky_name}: not implemented by the Bend shim>"

    def _operator(verb):
        def fail(cls, *args):
            return cls._wonky_fail(f"{verb} {cls._wonky_name}")
        return fail

    # `|` stays type.__or__ so that `Part | None` annotations keep working.
    __bool__ = _operator("Truth value of")
    __iter__ = _operator("Iterating over")
    __len__ = _operator("len() of")
    __contains__ = _operator("Membership test in")
    __float__ = __int__ = __index__ = _operator("Converting")
    __neg__ = __pos__ = __abs__ = _operator("Arithmetic on")
    for _dunder in ("add", "sub", "mul", "matmul", "truediv", "floordiv", "mod", "pow", "and", "xor", "lshift",
                    "rshift"):
        locals()[f"__{_dunder}__"] = locals()[f"__r{_dunder}__"] = _operator("Arithmetic on")
    del _dunder, _operator


def _sentinel(qualname, entry):
    return _Unimplemented(qualname.rsplit(".", 1)[-1], (), {
        "__module__": qualname.rsplit(".", 1)[0], "__qualname__": qualname.rsplit(".", 1)[-1],
        "_wonky_name": qualname, "_wonky_kind": entry["kind"], "_wonky_note": _note(qualname.rsplit(".", 1)[-1], entry),
        "__doc__": f"{qualname}: not implemented by the Bend shim (build123d {__version__} {entry['kind']})",
    }, _wonky_sentinel=True)


def _bind(name, entry, qualname):
    """Value for one table entry: a frozen number or enum, the re-exported stdlib object, or a use-site sentinel."""
    if entry["kind"] == "value" and "value" in entry:
        return entry["value"]
    if entry["kind"] == "enum" and entry["origin"] in ("public", "build123d"):
        return _Enum(name, [(member, value) for member, value in entry["members"]],
                     module="build123d", qualname=name)
    if "stdlib" in entry:
        value = _stdlib(entry["stdlib"])
        if value is not None:
            return value
    return _sentinel(qualname, entry)


def _top(name):
    """A top-level build123d name, binding a lazy stdlib re-export on first use."""
    namespace = globals()
    if name not in namespace:
        namespace[name] = _bind(name, _TABLE["names"][name], f"build123d.{name}")
    return namespace[name]


def _submodule(fullname, spec):
    """A read-only view of build123d.<sub>: its public names resolve through the same table."""
    module = _types.ModuleType(fullname, f"Bend shim view of {fullname} (build123d {__version__} names)")
    module.__path__ = []
    # Every public attribute of the real submodule (constants, aliases, mixins,
    # re-exports), so `from build123d.<sub> import X` fails only where build123d fails.
    names = spec.get("names", {})
    # `import *` binds the declared __all__, or all public names of a module without one.
    declared = spec.get("all")
    module.__all__ = list(declared) if isinstance(declared, list) else list(names)

    def __getattr__(name):
        if name.startswith("_") or name not in names:
            raise AttributeError(f"module {fullname!r} has no attribute {name!r}")
        entry = names[name]
        if entry is not None and entry["origin"] == "submodule" and entry.get("module") in _sys.modules:
            value = _sys.modules[entry["module"]]  # another shim view, e.g. topology.one_d
        else:
            value = _top(name) if entry is None else _bind(name, entry, f"{fullname}.{name}")
        setattr(module, name, value)
        return value

    module.__getattr__ = __getattr__
    return module


def _install_names():
    namespace = globals()
    views = {}
    for fullname, spec in sorted(_TABLE["submodules"].items()):
        if spec.get("importable"):
            views[fullname] = _sys.modules[fullname] = _submodule(fullname, spec)
    for fullname, view in views.items():
        parent, _, child = fullname.rpartition(".")
        if parent in views:
            setattr(views[parent], child, view)
    for name, entry in _TABLE["names"].items():
        if name in namespace or "stdlib" in entry:
            continue  # implemented above, or a stdlib re-export bound on first use (module __getattr__)
        view = views.get(f"build123d.{name}")
        namespace[name] = view if view is not None and entry["origin"] == "submodule" else _bind(name, entry, f"build123d.{name}")


_install_names()


def _bind_class_attributes():
    """Implemented class attributes, also on names that stay sentinels (e.g. Solid.make_box on Solid)."""
    for qualname, value in _CLASS_ATTRIBUTES.items():
        owner_name, _, attribute = qualname.partition(".")
        owner = globals().get(owner_name)
        if owner is None or not attribute:
            raise RuntimeError(f"CLASS_ATTRIBUTES entry {qualname!r} does not name a build123d class attribute")
        if isinstance(owner, _Unimplemented):
            type.__setattr__(owner, attribute, value)  # the sentinel's __setattr__ refuses model assignments
        else:
            setattr(owner, attribute, value)


_bind_class_attributes()


class _KernelGap:
    """A build123d method of an implemented class whose operation the Bend kernel lacks (``Shape.mirror``).

    Reading it is the capability error, at its use site, like any other
    unimplemented attribute of an implemented class, but the message names the
    missing kernel operation.
    """

    def __init__(self, attribute, note):
        self._attribute, self._note = attribute, note

    def __get__(self, instance, owner=None):
        name = (type(instance) if instance is not None else owner).__name__
        return _unsupported(f"{name}.{self._attribute} is not implemented by the Python frontend; {self._note}")


def _install_kernel_gaps():
    """Bind _KernelGap descriptors on implemented classes; implemented attributes and sentinels are left alone."""
    namespace = globals()
    for qualname, note in _KERNEL_GAPS.items():
        owner_name, _, attribute = qualname.partition(".")
        owner = namespace.get(owner_name)
        if not attribute or owner is None or isinstance(owner, _Unimplemented):
            continue  # top-level names and sentinel classes carry the note in their own messages
        if not any(attribute in vars(klass) for klass in owner.__mro__):
            type.__setattr__(owner, attribute, _KernelGap(attribute, note))


_install_kernel_gaps()

# `from build123d import *` binds exactly build123d 0.13.0's public names.
__all__ = list(_TABLE["all"])


def __getattr__(name):
    if not name.startswith("_") and name in _TABLE["names"]:
        return _top(name)
    if name.startswith("_"):
        raise AttributeError(name)
    raise AttributeError(f"module 'build123d' has no attribute {name!r} (not a public name of build123d {__version__})")
