//! Host operations behind the addon's `hostOp(words)` entry (HS1 seam, wire v3).
//!
//! Request: `[MAGIC, VERSION, op, ...payload]` as u32 words; a binary64 is two
//! words (low, high), the same bit transport as WC0 v3, so no decimal
//! conversion touches an input value (E9). Reply: `[status, ...payload]`, where
//! status 0 carries words or UTF-8-free text (one code point per word), and a
//! nonzero status carries a named reason as text.
//!
//! | op | request payload | reply |
//! |---:|---|---|
//! | 1 region | n, n x [u0 v0 u1 v1] | JSON: loops (segment uses), open wires |
//! | 2 prism | key[4] rev source[4] origin x z depth reverse loop n segs | WC0 v3 words |
//! | 3 measure | len words map? [12] nprobes probes[3] | JSON measurements |
//! | 4 step | name, n, n x (id, len words) | AP214 text |
//!
//! Every geometric decision happens in Rust on these exact inputs; the host
//! only routes and records. General measurements, no CAD-Acid-specific code.
use crate::affine::Affine;
use crate::extrude::{blind_prism, Prism, Refusal as ExtrudeRefusal};
use crate::polyhedron::{audit, Audited, Probe, Refused};
use crate::analytic as solid;
use wonky_contract::BodyKey;
use wonky_num::p2;
use wonky_sketch::region::{lines_region, Regions};
use wonky_sketch::Refusal as SketchRefusal;

pub const MAGIC: u32 = 0x3148_4b57; // little-endian bytes "WKH1"
pub const VERSION: u32 = 1;
pub const STATUS_OK: u32 = 0;
pub const STATUS_MALFORMED: u32 = 1;
/// A named refusal: the text is `<category>: <detail>`.
pub const STATUS_REFUSED: u32 = 7;

// BEGIN GENERATED HOST OPERATIONS
// Generated by scripts/native-bridge/gen-host-ops.mjs; do not edit this block.
// New operations take max+1 at merge time; see ../host-operations.json.
// The macro enumerates EVERY constant for the unit uniqueness test, including
// newly added operations not yet used by a dispatch match arm.
macro_rules! define_host_operations {
    ($( $(#[$meta:meta])* pub const $name:ident: u32 = $number:literal; )*) => {
        $( $(#[$meta])* pub const $name: u32 = $number; )*
        pub const HOST_OPERATION_NUMBERS: &[(&str, u32)] = &[
            $( (stringify!($name), $name), )*
        ];
    };
}
define_host_operations! {
    pub const OP_REGION: u32 = 1;
    pub const OP_PRISM: u32 = 2;
    pub const OP_LOFT: u32 = 6;
    pub const OP_MEASURE: u32 = 3;
    pub const OP_STEP: u32 = 4;
    pub const OP_STL: u32 = 5;
    pub const OP_PATTERN: u32 = 8;
    pub const OP_CUBOID: u32 = 10;
    pub const OP_PLACEMENT: u32 = 11;
    pub const OP_BOOLEAN: u32 = 12;
    pub const OP_DISTANCE: u32 = 13;
    pub const OP_EXTENTS: u32 = 14;
    pub const OP_CYLINDER: u32 = 15;
    pub const OP_QUERY: u32 = 16;
    pub const OP_SHELL: u32 = 17;
    pub const OP_CLOSEST_BOX_FACES: u32 = 18;
    pub const OP_SPHERE: u32 = 30;
    pub const OP_CLOSEST_EDGES: u32 = 32;
    pub const OP_FILLET: u32 = 31;
    pub const OP_CHAMFER: u32 = 33;
    /// mode (0 contains, 1 closest), frame origin x z, point, tie, segments,
    /// candidate count and region indices -> the indices of the selected regions
    /// among the candidates (region_query.rs).
    pub const OP_REGION_PICK: u32 = 34;
    /// lines, arcs, circle count and circles (x y r) -> the arrangement regions of
    /// the closed chains and circles (sketch_regions.rs).
    pub const OP_SKETCH_REGION: u32 = 38;
    /// key, frame, depth, reverse, lines, arcs, circles, region index -> the prism
    /// of one arrangement region.
    pub const OP_SKETCH_EXTRUDE: u32 = 39;
    /// deviation (f64), body count and WC0 words per body -> JSON `wonky-mesh/1`:
    /// the tessellation the STL is written from, before f32 quantisation, with the
    /// WC0 face id of every triangle and the sampled polyline of every WC0 edge
    /// (mesh.rs). An unattributable producer reports `faces: []`.
    pub const OP_MESH: u32 = 36;
    /// World-space analytic surface and curve carriers of every WC0 face and edge
    /// (millimetres, one rounding after the exact frame composition; see carriers.rs).
    pub const OP_CARRIERS: u32 = 37;
    /// mode (0 contains, 1 closest), frame origin x z, point, tie, lines, arcs,
    /// circles, candidate count and region indices -> the indices of the selected
    /// arrangement regions among the candidates (sketch_pick.rs).
    pub const OP_SKETCH_PICK: u32 = 40;
    pub const OP_CIRCLE_REGION: u32 = 20;
    pub const OP_PROFILE_REGION: u32 = 24;
    pub const OP_PROFILE_EXTRUDE: u32 = 25;
    pub const OP_ARC_REGION: u32 = 26;
    pub const OP_ARC_EXTRUDE: u32 = 27;
    /// key[4] rev, frame origin x z, depth, reverse, n, n binary64 sketch rule 3
    /// parameters (`wonky_contract::sketch3`: region 0 and one closed chain with a
    /// spline) -> WC0 v3 words of the curve-profile prism (`curve_profile`).
    /// Strand S9; FeatureScript reaches it through `skBezier` (strand S10) and
    /// `opExtrude` of the sketch.
    pub const OP_CURVE_EXTRUDE: u32 = 35;
    /// n, n binary64 sketch rule 3 parameters (region 0) -> `{"loops":[{}],
    /// "openWires":0}` when the entities form one simple closed chain with a spline
    /// (`curve_profile::profile`, the admission `OP_CURVE_EXTRUDE` runs), or that
    /// admission's refusal. Strand S10: `skSolve` of a sketch that holds a `skBezier`.
    pub const OP_CURVE_REGION: u32 = 41;
    pub const OP_CIRCLE_REVOLVE: u32 = 21;
    pub const OP_FRAME_CIRCLE_REVOLVE: u32 = 22;
    pub const OP_FRAME_POLYGON_REVOLVE: u32 = 23;
    pub const OP_SKETCH_POLYGON_REVOLVE: u32 = 28;
    /// Audited outward-rounded world enclosure for interference enumeration.
    pub const OP_CERTIFIED_BOUNDS: u32 = 42;
    /// Sufficient no-volume/contact or positive-clearance proof; null is inconclusive.
    pub const OP_PAIR_PROOF: u32 = 43;
    /// Assembly setup: audit and memoize an immutable source predicate once.
    pub const OP_PAIR_PREPARE: u32 = 44;
    pub const OP_RATIONAL_PLACEMENT: u32 = 45;
    pub const OP_RIGID_PLACEMENT: u32 = 46;
}
// END GENERATED HOST OPERATIONS

#[derive(Debug)]
enum Fail {
    Malformed(String),
    Refused(String),
}
type R<T> = Result<T, Fail>;

struct Reader<'a> {
    words: &'a [u32],
    at: usize,
}
impl Reader<'_> {
    fn u32(&mut self) -> R<u32> {
        let w = *self.words.get(self.at).ok_or_else(|| Fail::Malformed("request ends early".into()))?;
        self.at += 1;
        Ok(w)
    }
    fn f64(&mut self) -> R<f64> {
        let lo = self.u32()? as u64;
        let x = f64::from_bits(lo | ((self.u32()? as u64) << 32));
        if !x.is_finite() {
            return Err(Fail::Malformed("non-finite binary64".into()));
        }
        Ok(x)
    }
    fn f3(&mut self) -> R<[f64; 3]> {
        Ok([self.f64()?, self.f64()?, self.f64()?])
    }
    fn count(&mut self, per: usize) -> R<usize> {
        let n = self.u32()? as usize;
        if n.saturating_mul(per) > self.words.len() - self.at {
            return Err(Fail::Malformed("count exceeds the request".into()));
        }
        Ok(n)
    }
    fn words(&mut self) -> R<&[u32]> {
        let n = self.count(1)?;
        let s = &self.words[self.at..self.at + n];
        self.at += n;
        Ok(s)
    }
    fn text(&mut self) -> R<String> {
        self.words()?.iter().map(|&c| char::from_u32(c).ok_or_else(|| Fail::Malformed("text".into()))).collect()
    }
    fn segments(&mut self) -> R<Vec<[f64; 4]>> {
        let n = self.count(8)?;
        (0..n).map(|_| Ok([self.f64()?, self.f64()?, self.f64()?, self.f64()?])).collect()
    }
    fn circles(&mut self) -> R<Vec<[f64; 3]>> {
        let n = self.count(6)?;
        (0..n).map(|_| self.f3()).collect()
    }
    fn arcs(&mut self) -> R<Vec<[f64; 6]>> {
        let n=self.count(12)?;
        (0..n).map(|_|Ok([self.f64()?,self.f64()?,self.f64()?,self.f64()?,self.f64()?,self.f64()?])).collect()
    }
    fn finish(&self) -> R<()> {
        if self.at != self.words.len() {
            return Err(Fail::Malformed("trailing request words".into()));
        }
        Ok(())
    }
    /// The entities of the closing field of `OP_CURVE_REGION` and
    /// `OP_CURVE_EXTRUDE`: n, then n binary64 sketch rule 3 parameters. Only
    /// region 0, the one closed chain, is admitted.
    fn sketch3(&mut self) -> R<Vec<wonky_contract::sketch3::Entity>> {
        let n = self.count(2)?;
        let parameters = (0..n).map(|_| self.f64()).collect::<R<Vec<_>>>()?;
        self.finish()?;
        let (region, entities) = wonky_contract::sketch3::parse(&parameters)
            .map_err(|e| Fail::Malformed(format!("sketch rule 3 parameters: {e:?}")))?;
        if region != 0 {
            return Err(Fail::Refused("curve-profile/region-unsupported".into()));
        }
        Ok(entities)
    }
}

fn sketch_refusal(r: SketchRefusal) -> Fail {
    let name = match r {
        SketchRefusal::Branching => "sketch/branching",
        SketchRefusal::UnsupportedIntersection => "sketch/intersection",
        SketchRefusal::Nested => "sketch/nested-loops",
        SketchRefusal::Degenerate => "sketch/degenerate",
        SketchRefusal::NumericDecision => "sketch/numeric-range",
        _ => "sketch/invalid",
    };
    Fail::Refused(format!("{name}: {r:?}"))
}

fn regions(segments: &[[f64; 4]]) -> R<Regions> {
    let s: Vec<_> = segments.iter().map(|s| [p2(s[0], s[1]), p2(s[2], s[3])]).collect();
    lines_region(&s).map_err(sketch_refusal)
}

fn num(x: f64) -> String {
    // Shortest round-trip digits; never NaN/Inf (guarded by the callers).
    let x = if x == 0.0 { 0.0 } else { x };
    format!("{x:?}")
}
fn nums(v: &[f64]) -> String {
    format!("[{}]", v.iter().map(|&x| num(x)).collect::<Vec<_>>().join(","))
}
fn refused(e: Refused) -> Fail {
    Fail::Refused(e.0)
}

/// Analytic face classes from the checked WC0 boundary, not an exporter or
/// modelling-family label. Count faces (a surface can support several faces).
fn surface_types_json(body: &wonky_contract::Body) -> String {
    use wonky_contract::SurfaceGeometry as S;
    let mut counts = std::collections::BTreeMap::<&str, usize>::new();
    for face in &body.faces {
        let name = match &body.surfaces[face.surface.0 as usize].geometry {
            S::Plane { .. } => "Plane",
            S::Cylinder { .. } => "Cylinder",
            S::Cone { .. } | S::ConeSlope { .. } | S::ConeMeridian { .. } => "Cone",
            S::Sphere { .. } => "Sphere",
            S::Torus { .. } => "Torus",
            S::LinearExtrusion { .. } => "SurfaceOfExtrusion",
        };
        *counts.entry(name).or_default() += 1;
    }
    format!("{{{}}}", counts.iter().map(|(name, n)| format!("\"{name}\":{n}")).collect::<Vec<_>>().join(","))
}

enum HostBody { Solid(solid::Solid), Torus(crate::revolve::Torus), Sector(crate::revolve_sector::Sector) }
// Audits are pure functions of the WC0 words (sources, parameters and caps
// all live in the body), and the host sees the same body many times per
// feature (Boolean input, volume, queries). Successful audits are memoized
// by their FULL word sequence, never by the body id or revision. A hit also
// witnesses the structural wire check: exactly these immutable bytes passed it.
// Keep enough entries for a complete assembly/batched Boolean, with a separate
// word budget so large histories cannot make the LRU grow without bound.
thread_local! {
    static AUDITED: std::cell::RefCell<Vec<(Vec<u32>, solid::Solid)>> = const { std::cell::RefCell::new(Vec::new()) };
}
const AUDIT_MEMO: usize = 128;
const AUDIT_WORDS: usize = 2_000_000;
fn cached_audit(words: &[u32]) -> Option<solid::Solid> {
    AUDITED.with(|m| {
        let mut m = m.borrow_mut();
        let i = m.iter().position(|(w, _)| w.as_slice() == words)?;
        let entry = m.remove(i);
        let solid = entry.1.clone();
        m.push(entry);
        Some(solid)
    })
}
fn memo_audit(words: &[u32], checked: &wonky_contract::CheckedBody) -> Result<solid::Solid, Refused> {
    if let Some(s) = cached_audit(words) { return Ok(s); }
    let s = solid::audit(checked)?;
    if words.len() <= AUDIT_WORDS {
        AUDITED.with(|m| {
            let mut m = m.borrow_mut();
            let mut used = m.iter().map(|(w, _)| w.len()).sum::<usize>();
            while m.len() >= AUDIT_MEMO || used + words.len() > AUDIT_WORDS {
                used -= m.remove(0).0.len();
            }
            m.push((words.to_vec(), s.clone()));
        });
    }
    Ok(s)
}
fn decode_any(words: &[u32]) -> R<HostBody> {
    if let Some(s) = cached_audit(words) { return Ok(HostBody::Solid(s)); }
    let checked = wonky_wire::v3::decode(words).map_err(|e| Fail::Malformed(format!("WC0 v3 body: {e:?}")))?;
    if crate::revolve_full::candidate(checked.body()) {
        memo_audit(words, &checked).map(HostBody::Solid).map_err(refused)
    } else if !crate::arc_profile::candidate(checked.body()) && !crate::prism_stack::candidate(checked.body()) && checked.body().surfaces.iter().any(|s| matches!(s.geometry, wonky_contract::SurfaceGeometry::Torus { .. })) {
        crate::revolve::audit(&checked).map(HostBody::Torus).map_err(refused)
    } else if checked.body().constructions.iter().any(|n| matches!(n.operation, wonky_contract::Operation::Revolve {})) {
        crate::revolve_sector::audit(&checked).map(HostBody::Sector).map_err(refused)
    } else { memo_audit(words, &checked).map(HostBody::Solid).map_err(refused) }
}
fn decode_body(words: &[u32]) -> R<Audited> {
    let checked = wonky_wire::v3::decode(words).map_err(|e| Fail::Malformed(format!("WC0 v3 body: {e:?}")))?;
    audit(&checked).map_err(refused)
}

fn decode_solid(words: &[u32]) -> R<solid::Solid> {
    if let Some(s) = cached_audit(words) { return Ok(s); }
    let checked = wonky_wire::v3::decode(words).map_err(|e| Fail::Malformed(format!("WC0 v3 body: {e:?}")))?;
    memo_audit(words, &checked).map_err(refused)
}

// Prepared predicates share immutable audited construction data, keyed by all
// bytes just like the audit memo. They retain no B-rep copies. Assembly setup is
// timed separately from each pair and included in the end-to-end report time.
thread_local! {
    static PAIR_SHAPES: std::cell::RefCell<Vec<(Vec<u32>, std::sync::Arc<crate::interference_proof::Shape>)>> = const { std::cell::RefCell::new(Vec::new()) };
}
const SHAPE_WORDS: usize = 8_000_000;
fn prepared_shape(words: &[u32]) -> R<std::sync::Arc<crate::interference_proof::Shape>> {
    let cached = PAIR_SHAPES.with(|m| {
        let mut m=m.borrow_mut();
        let i=m.iter().position(|(w,_)|w.as_slice()==words)?;
        let entry=m.remove(i);let shape=entry.1.clone();m.push(entry);Some(shape)
    });
    if let Some(shape)=cached {return Ok(shape);}
    let shape=std::sync::Arc::new(crate::interference_proof::shape(&decode_solid(words)?).map_err(refused)?);
    if words.len()<=SHAPE_WORDS {
        PAIR_SHAPES.with(|m| {
            let mut m=m.borrow_mut();let mut used=m.iter().map(|(w,_)|w.len()).sum::<usize>();
            while m.len()>=AUDIT_MEMO || used+words.len()>SHAPE_WORDS {used-=m.remove(0).0.len();}
            m.push((words.to_vec(),shape.clone()));
        });
    }
    Ok(shape)
}
pub fn measure_json(a: &Audited, map: Option<[[f64; 4]; 3]>, probes: &[[f64; 3]]) -> Result<String, Refused> {
    let volume = a.volume_mm3()?;
    let faces = a.face_areas_mm2()?;
    // Sum face observations exactly before rounding; a long face list must not
    // invalidate the fixed relative area certificate by accumulation error.
    let mut g = wonky_num::expansion::Guard::new();
    let mut total = Vec::new();
    for &face in &faces { total = wonky_num::expansion::sum(&total, &[face], &mut g); }
    if !g.exact() { return Err(Refused("observe/area-range".into())); }
    let area = crate::rounding::round(&total).map_err(|_| Refused("observe/area-range".into()))?;
    let (centroid, centroid_bound) = a.centroid_with_bound_mm()?;
    let perimeters = a.face_perimeters_mm()?;
    let (lo, hi) = a.bbox_mm(None)?;
    let mapped = match map {
        Some(m) => {
            let (l, h) = a.bbox_mm(Some(m))?;
            format!("{{\"min\":{},\"max\":{}}}", nums(&l), nums(&h))
        }
        None => "null".into(),
    };
    let t = a.topology();
    let defect = a.frame.orthonormality_defect().map_err(|_| Refused("observe/frame".into()))?;
    let tolerance = a.export_tolerance_mm()?;
    let probes: Vec<String> = probes
        .iter()
        .map(|&q| match a.distance_mm(q) {
            Probe::Measured { distance_mm, inside, bound_mm } => format!("{{\"distanceMm\":{},\"inside\":{inside},\"boundMm\":{}}}", num(distance_mm), num(bound_mm)),
            Probe::Refused(r) => format!("{{\"refused\":\"{r}\"}}"),
        })
        .collect();
    let world = a.world_vertices_mm()?;
    let body = &a.body;
    let reflected = a.frame.reversed().map_err(|_| Refused("observe/frame-orientation".into()))?;
    let faces_json: Vec<String> = body.faces.iter().map(|f| {
        let loops: Vec<String> = f.loops.iter().map(|l| {
            let lp=&body.loops[l.0 as usize];
            let mut coedges = lp.coedges.clone();
            if reflected { coedges.reverse(); }
            format!("[{}]",coedges.iter().map(|c| {let co=&body.coedges[c.0 as usize];format!("[{},{}]",co.edge.0,co.forward != reflected)}).collect::<Vec<_>>().join(","))
        }).collect();
        format!("[{}]",loops.join(","))
    }).collect();
    Ok(format!(
        concat!(
            "{{{}\"basis\":\"native-f64-construction\",\"certificate\":\"{}\",\"axis\":{},\"boundToConstruction\":{},",
            "\"volumeMm3\":{},\"volumeRelBound\":{},\"areaMm2\":{},\"areaRelBound\":{},\"faceAreasMm2\":{},\"facePerimetersMm\":{},",
            "\"centroidMm\":{},\"centroidBoundMm\":{},\"bboxMm\":{{\"min\":{},\"max\":{}}},\"mappedBboxMm\":{},",
            "\"topology\":{{\"bodies\":{},\"shells\":{},\"faces\":{},\"edges\":{},\"vertices\":{},\"loops\":{},\"ringEdges\":{},\"closedToroidalFaces\":{},\"genus\":{},\"singularPoints\":{},\"pinchPoints\":{}}},",
            "\"validity\":{{\"brep\":true,\"closed\":true,\"positive\":{}}},\"toleranceMm\":{},",
            "\"frame\":{{\"orthonormalityDefect\":{}}},\"probes\":[{}],",
            "\"projection\":{{\"vertices\":[{}],\"edges\":[{}],\"faces\":[{}]}}}}"
        ),
        {
            let regularization = a.arcs.as_ref().and_then(|s| s.regularization.as_ref()).map(|r| format!("\"regularization\":{r},")).unwrap_or_default();
            let fit = a.body.constructions.iter().any(|n| n.operation == (wonky_contract::Operation::Sketch {}) && n.rule_version == 3 &&
                wonky_contract::sketch3::parse(&n.parameters.iter().map(|p|p.get()).collect::<Vec<_>>()).is_ok_and(|(_,es)|es.iter().any(|e|matches!(e,wonky_contract::sketch3::Entity::Fit {..}))));
            let exact = a.volume_exact_mm3()?.map(|v| format!("\"volumeExactMm3\":{{\"numerator\":\"{}\",\"denominator\":\"{}\"}},", v.numer(), v.denom())).unwrap_or_default();
            format!("{regularization}{exact}{}",if fit { "\"fitResidual\":0," } else { "" })
        },
        if a.arcs.as_ref().is_some_and(|s|s.rim.is_some()) { "ConvexTangentRim" } else if crate::curve_profile::candidate(&a.body) { "CurveProfilePrism" } else if a.arcs.is_some() { "ThreePointArcPrism" } else if a.chamfer.is_some() { "PlanarChamfer" } else if a.corner.is_some() { "RollingBallCorner" } else if a.rounded.is_some() { "RollingBallPrism" } else if a.orthogonal.is_some() { "OrthogonalCells" } else if crate::planar_boolean::candidate(&a.body) { "ExactPlaneArrangement" } else if crate::loft::candidate(&a.body) { "RuledPlanarLoft" } else { "AxisPrism" },
        if crate::planar_boolean::candidate(&a.body) || crate::loft::candidate(&a.body) { "null".into() } else { a.axis.to_string() },
        a.bound_to_construction,
        num(volume),
        num(if let Some(s)=&a.arcs { let v=s.volume(a)?; v.r/v.lo() } else if let Some(s)=&a.chamfer { let v=s.volume()?; v.r/v.lo() } else if let Some(s)=&a.corner { let v=s.volume(a)?; v.r/v.lo() } else if let Some(s)=&a.rounded { let v=s.volume(a)?; v.r/v.lo() } else { 2.0 * f64::EPSILON }),
        num(area),
        num(if let Some(s)=&a.arcs { let v=s.areas(a)?.into_iter().fold(wonky_num::Iv::point(0.),|x,y|x+y); v.r/v.lo() } else if let Some(s)=&a.chamfer { let v=s.areas()?.into_iter().fold(wonky_num::ball::Iv::point(0.),|x,y|x+y); v.r/v.lo() } else if let Some(s)=&a.corner { let v=s.areas(a)?.into_iter().fold(wonky_num::ball::Iv::point(0.),|x,y|x+y); v.r/v.lo() } else if let Some(s)=&a.rounded { let v=s.areas(a)?.into_iter().fold(wonky_num::ball::Iv::point(0.),|x,y|x+y); v.r/v.lo() } else { 64.0 * f64::EPSILON + 3.0 * defect }),
        nums(&faces),
        nums(&perimeters),
        nums(&centroid),
        nums(&centroid_bound),
        nums(&lo),
        nums(&hi),
        mapped,
        t.bodies,
        t.shells,
        t.faces,
        t.edges,
        t.vertices,
        t.loops,
        t.ring_edges,
        t.closed_toroidal_faces,
        t.genus,
        t.singular_points,
        t.pinch_points,
        volume > 0.0,
        num(tolerance),
        num(defect),
        probes.join(","),
        world.iter().map(|v| nums(v)).collect::<Vec<_>>().join(","),
        body.edges.iter().map(|e| format!("[{},{}]", e.vertices[0].0, e.vertices[1].0)).collect::<Vec<_>>().join(","),
        faces_json.join(","),
    ))
}

// Two host ops with one number would leave the later match arm unreachable and
// silently answer its requests with the earlier op (OP_MESH and OP_CURVE_REGION
// were both 36 when strands S10 and viewer-rust met): a compile error instead.
#[deny(unreachable_patterns)]
fn run(words: &[u32]) -> R<Vec<u32>> {
    let mut r = Reader { words, at: 0 };
    if r.u32()? != MAGIC || r.u32()? != VERSION {
        return Err(Fail::Malformed("host op magic/version".into()));
    }
    let text = |s: String| -> Vec<u32> { std::iter::once(STATUS_OK).chain(s.chars().map(|c| c as u32)).collect() };
    let op = r.u32()?;
    match op {
        OP_SHELL => {
            let a = decode_body(r.words()?)?;
            let face = r.u32()? as usize;
            let thickness = r.f64()?;
            r.finish()?;
            let body = crate::planar_shell::shell(&a, face, thickness).map_err(refused)?;
            let words = wonky_wire::v3::encode(&body).map_err(|_| Fail::Refused("shell/wire".into()))?;
            decode_body(&words)?;
            Ok(std::iter::once(STATUS_OK).chain(words).collect())
        }
        OP_CLOSEST_BOX_FACES => {
            let a = decode_body(r.words()?)?;
            let point = r.f3()?;
            let tolerance = r.f64()?;
            let n = r.count(1)?;
            let faces = (0..n).map(|_| r.u32().map(|x| x as usize)).collect::<R<Vec<_>>>()?;
            r.finish()?;
            let selected = crate::planar_shell::closest_faces(&a, &faces, point, tolerance).map_err(refused)?;
            Ok(std::iter::once(STATUS_OK).chain(selected.into_iter().map(|x| x as u32)).collect())
        }
        OP_CLOSEST_EDGES => {
            let point = r.f3()?;
            let tie = r.f64()?;
            let n = r.count(2)?;
            let mut bodies = Vec::with_capacity(n);
            let mut indices = Vec::with_capacity(n);
            for _ in 0..n {
                bodies.push(decode_solid(r.words()?)?);
                indices.push(r.u32()? as usize);
            }
            r.finish()?;
            let candidates: Vec<_> = bodies.iter().zip(indices).collect();
            let selected = crate::edge_query::closest_solids(&candidates, point, tie).map_err(refused)?;
            Ok(std::iter::once(STATUS_OK).chain(selected.into_iter().map(|i| i as u32)).collect())
        }
        op @ (OP_FILLET | OP_CHAMFER) => {
            let body = decode_solid(r.words()?)?;
            let radius = r.f64()?;
            let n = r.count(1)?;
            let edges = (0..n).map(|_| r.u32().map(|i| i as usize)).collect::<R<Vec<_>>>()?;
            let tangent=if op==OP_CHAMFER && r.at<r.words.len() {match r.u32()? {0=>false,1=>true,_=>return Err(Fail::Malformed("chamfer propagation flag".into()))}} else {false};
            r.finish()?;
            if tangent && !matches!(&body,solid::Solid::Planar(_) | solid::Solid::Model(_, _)) {return Err(Fail::Refused("blend/tangent-propagation-carrier-unavailable".into()));}
            let blended = match &body {
                solid::Solid::Planar(a) if op==OP_CHAMFER && tangent => crate::model_boolean::chamfer_with_propagation(a,&edges,radius,true),
                solid::Solid::Model(a, _) if op == OP_CHAMFER => crate::model_boolean::chamfer_with_propagation(a, &edges, radius,tangent),
                solid::Solid::Model(a, _) => crate::fillet_general::apply(a,&edges,radius),
                solid::Solid::Planar(a) if op == OP_CHAMFER => match crate::chamfer::equal_offsets(a, &edges, radius) {
                    Err(e) if e.0 == "chamfer/requires-orthogonal-single-shell" || e.0 == "profile-blend/tangent-length-not-rational" => crate::model_boolean::chamfer(a, &edges, radius),
                    result => result,
                },
                solid::Solid::Planar(a) => crate::fillet::constant_radius(a, &edges, radius),
                solid::Solid::Cylinder(c) if op == OP_CHAMFER => crate::chamfer_rim::equal_offsets(c, &edges, radius),
                solid::Solid::Cylinder(_) => Err(Refused("fillet/circular-rim-toroidal-blend-unimplemented".into())),
                // Straight box edges and hole rims are trimmed in one operation:
                // planar setbacks plus exact two-ring countersink cones.
                solid::Solid::Perforated(p) if op == OP_CHAMFER => crate::perforated_chamfer::equal_offsets(p, &edges, radius),
                solid::Solid::Perforated(_) | solid::Solid::PrismHoles(_) if op == OP_FILLET => crate::fillet_general::cut_generators(&body,&edges,radius),
                // Admission-last (F2c): an offset the binary64 stack family
                // cannot state chamfers on the stack's exact general Model.
                solid::Solid::PrismStack(s) if op == OP_CHAMFER => match crate::stack_blend::apply(s, &edges, radius, true) {
                    Err(e) if e.0 == "fillet/rim-offset-not-representable" => crate::model_boolean::chamfer_stack(s, &edges, radius),
                    result => result,
                },
                solid::Solid::PrismStack(s) => crate::stack_blend::apply(s, &edges, radius, false),
                _ => Err(Refused(if op == OP_CHAMFER { "chamfer/analytic-blend-unimplemented" } else { "fillet/analytic-blend-unimplemented" }.into())),
            }.map_err(refused)?;
            let words = wonky_wire::v3::encode(&blended).map_err(|_| Fail::Refused("fillet/wire".into()))?;
            decode_solid(&words)?;
            Ok(std::iter::once(STATUS_OK).chain(words).collect())
        }
        OP_PATTERN => {
            let body = r.words()?.to_vec();
            let key = BodyKey {
                id: [r.u32()?, r.u32()?, r.u32()?, r.u32()?],
                revision: r.u32()?,
            };
            let rows = [r.f3()?, r.f3()?, r.f3()?];
            let translation = r.f3()?;
            let local = if r.at < r.words.len() { Some((Affine { origin:r.f3()?, x:r.f3()?, z:r.f3()? }, r.u32()?)) } else { None };
            r.finish()?;
            let post = if let Some((chart,k)) = local {
                if k > 3 || rows != [[1.,0.,0.],[0.,1.,0.],[0.,0.,1.]] || translation != [0.;3] { return Err(Fail::Malformed("local quarter placement".into())); }
                let checked = wonky_wire::v3::decode(&body).map_err(|e| Fail::Refused(format!("placement/wire: {e:?}")))?;
                crate::pattern::require_local_chart(checked.body(), chart, k).map_err(refused)?;
                crate::placement::Post::LocalQuarter(k)
            } else { crate::placement::Post::Rows { translation, rows } };
            let copy = match decode_solid(&body)? {
                solid::Solid::Model(a, _) => crate::model_boolean::place(&a,key,&post).map_err(refused)?,
                solid::Solid::Planar(a) => crate::pattern::place(&a,key,&post).map_err(refused)?.body,
                // Families without a placement owner keep their source and are
                // read through the exactly moved source Model, as in `transform`.
                solid::Solid::Revolved(crate::revolve_full::FullRevolve { body, .. })
                | solid::Solid::Placed(crate::model_curved::Placed { body, .. }) => crate::pattern::place_body(&body,key,&post).map_err(refused)?,
                solid::Solid::Cylinder(c) => crate::cylinder::copy(&c,key,&post).map_err(refused)?,
                _ => return Err(Fail::Refused("pattern/carrier-family".into())),
            };
            let words = wonky_wire::v3::encode(&copy)
                .map_err(|e| Fail::Refused(format!("pattern/contract: {e:?}")))?;
            Ok(std::iter::once(STATUS_OK).chain(words).collect())
        }
        OP_SPHERE => {
            let key = BodyKey { id:[r.u32()?,r.u32()?,r.u32()?,r.u32()?],revision:0 };
            let (center, radius) = (r.f3()?, r.f64()?); r.finish()?;
            let body = crate::sphere::sphere(key, center, radius).map_err(refused)?;
            let words = wonky_wire::v3::encode(&body).map_err(|_|Fail::Refused("sphere/wire".into()))?;
            decode_solid(&words)?;
            Ok(std::iter::once(STATUS_OK).chain(words).collect())
        }
        OP_QUERY => {
            let a = decode_solid(r.words()?)?;
            let mode = r.u32()?;
            let count = r.count(2)?;
            let selected = (0..count).map(|_| Ok(crate::query::Entity { kind: r.u32()?, index: r.u32()? })).collect::<R<Vec<_>>>()?;
            let result = match mode {
                0 => crate::query::owned(&a, r.u32()?),
                1 => crate::query::geometry(&a, &selected, &r.text()?),
                2 => crate::query::adjacent(&a, &selected, r.u32()?),
                3 => crate::query::coincides(&a, &selected, r.f3()?, r.f3()?),
                4 => crate::query::parallel_edges(&a, &selected, r.f3()?),
                5 => {
                    let frame = Affine { origin: r.f3()?, x: r.f3()?, z: r.f3()? };
                    crate::query::coincides_in_frame(&a, &selected, frame, r.f3()?, r.f3()?)
                }
                _ => return Err(Fail::Malformed("query operation".into())),
            }.map_err(refused)?;
            r.finish()?;
            let mut reply = vec![STATUS_OK, result.len() as u32];
            for e in result { reply.extend([e.kind, e.index]); }
            Ok(reply)
        }
        OP_CYLINDER => {
            let key = BodyKey { id:[r.u32()?,r.u32()?,r.u32()?,r.u32()?],revision:0 };
            let spec=crate::cylinder::Spec {bottom:r.f3()?,top:r.f3()?,radius:r.f64()?};r.finish()?;
            let body=crate::cylinder::create(key,spec).map_err(refused)?;
            let words=wonky_wire::v3::encode(&body).map_err(|_|Fail::Refused("cylinder/wire".into()))?;
            decode_solid(&words)?;
            Ok(std::iter::once(STATUS_OK).chain(words).collect())
        }
        OP_CUBOID => {
            let key = BodyKey { id:[r.u32()?,r.u32()?,r.u32()?,r.u32()?],revision:0 };
            let (a,b) = (r.f3()?,r.f3()?); r.finish()?;
            let body=crate::orthogonal::cuboid(key,a,b).map_err(refused)?;
            let words=wonky_wire::v3::encode(&body).map_err(|_|Fail::Refused("cuboid/wire".into()))?;
            decode_body(&words)?;
            Ok(std::iter::once(STATUS_OK).chain(words).collect())
        }
        OP_RATIONAL_PLACEMENT => {
            let a=decode_solid(r.words()?)?;
            let rows=[r.f3()?,r.f3()?,r.f3()?]; let denominator=r.f64()?; r.finish()?;
            let q = crate::planar_geometry::q;
            if denominator <= 0. { return Err(Fail::Refused("placement/rational-not-isometric".into())); }
            let columns = [0, 1, 2].map(|j| [0, 1, 2].map(|k| q(rows[k][j]) / q(denominator)));
            for i in 0..3 { for j in 0..3 {
                if crate::planar_geometry::dot(&columns[i], &columns[j]) != q(if i == j { 1. } else { 0. }) {
                    return Err(Fail::Refused("placement/rational-not-isometric".into()));
                }
            } }
            let post=crate::placement::Post::Rational {rows,denominator};
            let solid::Solid::Planar(a)=a else {return Err(Fail::Refused("placement/rational-curved-carrier-unimplemented".into()));};
            let mut key=a.body.key.clone();key.revision=key.revision.checked_add(1).ok_or_else(||Fail::Refused("placement/revision-range".into()))?;
            let body=crate::pattern::place(&a,key,&post).map_err(refused)?;
            // The post map was proved isometric above. An interpreter source
            // frame remains its exact binary64 affine input, not an idealized
            // rotation: its Gram defect must not invalidate a rigid post map.
            let words=wonky_wire::v3::encode(&body.body).map_err(|_|Fail::Refused("placement/wire".into()))?;decode_solid(&words)?;
            Ok(std::iter::once(STATUS_OK).chain(words).collect())
        }
        OP_PLACEMENT | OP_RIGID_PLACEMENT => {
            let a=decode_solid(r.words()?)?;
            let frame=Affine {origin:r.f3()?,x:r.f3()?,z:r.f3()?};r.finish()?;
            if op==OP_RIGID_PLACEMENT {
                let q=crate::planar_geometry::q;
                let x=frame.x.map(q);let z=frame.z.map(q);
                if crate::planar_geometry::dot(&x,&x)!=q(1.) || crate::planar_geometry::dot(&z,&z)!=q(1.) || crate::planar_geometry::dot(&x,&z)!=q(0.) {return Err(Fail::Refused("placement/rotation-not-exact".into()));}
            }
            let body=a.transform(frame).map_err(refused)?;
            let words=wonky_wire::v3::encode(&body).map_err(|_|Fail::Refused("placement/wire".into()))?;
            decode_solid(&words)?;
            Ok(std::iter::once(STATUS_OK).chain(words).collect())
        }
        OP_BOOLEAN => {
            let key = BodyKey { id:[r.u32()?,r.u32()?,r.u32()?,r.u32()?],revision:0 };
            let op=r.u32()?; if op>2 { return Err(Fail::Malformed("boolean operation".into())); }
            let n=r.count(1)?;let inputs=(0..n).map(|_|decode_solid(r.words()?)).collect::<R<Vec<_>>>()?;
            let cap=if r.at<r.words.len() {Some(r.f64()?)} else {None}; r.finish()?;
            if cap.is_some_and(|c| c<0.) {return Err(refused(Refused("regularization/coincidence/invalid-cap".into())));}
            #[cfg_attr(not(feature = "plant_shadow_mutates"), allow(unused_mut))]
            let mut family=solid::boolean(key,op as u8,&inputs);
            // Opt-in shadow of the general Boolean (boolean3d C11): reads the
            // operands and this result, reports elsewhere, replies nothing.
            if crate::shadow::enabled() {
                #[cfg(not(feature = "plant_shadow_mutates"))]
                crate::shadow::observe(op as u8,&inputs,&family);
                #[cfg(feature = "plant_shadow_mutates")]
                crate::shadow::observe_mut(op as u8,&inputs,&mut family);
            }
            let bodies=family.map_err(|e| {
                // A bounded carrier match alone is not a Boolean. Preserve the
                // exact success path and fail atomically with candidate evidence.
                if let Some(cap)=cap {
                    match crate::carrier_coincidence::refusal(&inputs,cap,&e.0) {
                        Ok(Some(report)) => return Fail::Refused(report),
                        Err(reason) => return refused(reason),
                        Ok(None) => {},
                    }
                }
                refused(e)
            })?;
            let owners=solid::boolean_identity_sources(op as u8,&inputs,&bodies).map_err(refused)?;
            let mut reply=vec![STATUS_OK,bodies.len() as u32];
            for (i,mut body) in bodies.into_iter().enumerate() {
                body.key.revision=i as u32;
                let words=wonky_wire::v3::encode(&body).map_err(|_|Fail::Refused("boolean/wire".into()))?;
                decode_solid(&words)?;reply.push(words.len() as u32);reply.extend(words);
            }
            // HS1 Boolean reply: count, count WC0 blocks, then count source
            // indices. This history is separate from WC0 construction keys.
            reply.extend(owners.into_iter().map(|i| i as u32));
            Ok(reply)
        }
        OP_PAIR_PREPARE => {
            let shape=prepared_shape(r.words()?)?;r.finish()?;
            drop(shape);
            Ok(text("null".into()))
        }
        OP_PAIR_PROOF => {
            let (a,b)=(prepared_shape(r.words()?)?,prepared_shape(r.words()?)?);r.finish()?;
            let proof=crate::interference_proof::pair(&a,&b).map_err(refused)?;
            Ok(text(proof))
        }
        OP_DISTANCE => {
            let (a,b)=(decode_solid(r.words()?)?,decode_solid(r.words()?)?);r.finish()?;
            let (distance,bound)=solid::distance(&a,&b).map_err(refused)?;
            Ok(text(format!("{{\"distanceMm\":{},\"boundMm\":{}}}",num(distance),num(bound))))
        }
        OP_EXTENTS => {
            // Revolved tori and sectors are their own audits: name them, rather
            // than reporting the planar audit's failure on a curved body.
            let a=decode_any(r.words()?)?;r.finish()?;
            match a {
                HostBody::Solid(a) => Ok(text(nums(&a.extents().map_err(refused)?))),
                HostBody::Torus(_) => Err(Fail::Refused("bbox/torus-source-extents".into())),
                HostBody::Sector(_) => Err(Fail::Refused("bbox/sector-source-extents".into())),
            }
        }
        OP_ARC_REGION => {
            let lines=r.segments()?;let arcs=r.arcs()?;
            let cap=if r.at<r.words.len(){Some(r.f64()?)}else{None};r.finish()?;
            let (regions, report)=if let Some(cap)=cap {
                let (regions, report)=crate::arc_profile::regularized_regions(&lines,&arcs,cap).map_err(refused)?;
                (regions,format!(",\"regularization\":{report}"))
            } else {(crate::arc_profile::regions(&lines,&arcs).map_err(refused)?,String::new())};
            let loops=vec!["{}";regions.profiles.len()].join(",");
            Ok(text(format!("{{\"loops\":[{loops}],\"openWires\":{}{report}}}",regions.open_wires)))
        }
        OP_ARC_EXTRUDE => {
            let key=BodyKey{id:[r.u32()?,r.u32()?,r.u32()?,r.u32()?],revision:r.u32()?};
            let frame=Affine{origin:r.f3()?,x:r.f3()?,z:r.f3()?};let depth=r.f64()?;let reverse=r.u32()?;
            if reverse>1{return Err(Fail::Malformed("arc reverse flag".into()));}
            let lines=r.segments()?;let arcs=r.arcs()?;
            let region=if r.at<r.words.len(){r.u32()? as usize}else{0};
            let cap=if r.at<r.words.len(){Some(r.f64()?)}else{None};r.finish()?;
            let body=if let Some(cap)=cap {
                crate::arc_profile::build_regularized_region(key,frame,&lines,&arcs,depth,reverse==1,region,cap)
            } else {crate::arc_profile::build_region(key,frame,&lines,&arcs,depth,reverse==1,region)}.map_err(refused)?;
            let words=wonky_wire::v3::encode(&body).map_err(|_|Fail::Refused("arc-profile/wire".into()))?;
            decode_solid(&words)?;
            Ok(std::iter::once(STATUS_OK).chain(words).collect())
        }
        OP_SKETCH_REGION => {
            let lines=r.segments()?;let arcs=r.arcs()?;let circles=r.circles()?;r.finish()?;
            let regions=crate::sketch_regions::regions(&lines,&arcs,&circles).map_err(refused)?;
            let loops=regions.iter().map(|g|format!("{{\"inner\":{},\"contested\":{},\"adjacent\":[{}]}}",g.inner,g.contested,g.adjacent.iter().map(|a|a.to_string()).collect::<Vec<_>>().join(","))).collect::<Vec<_>>().join(",");
            Ok(text(format!("{{\"loops\":[{loops}],\"openWires\":0,\"arrangement\":true}}")))
        }
        OP_SKETCH_PICK => {
            let mode = r.u32()?;
            if mode != crate::region_query::CONTAINS && mode != crate::region_query::CLOSEST {
                return Err(Fail::Malformed("sketch pick mode".into()));
            }
            let frame = Affine { origin: r.f3()?, x: r.f3()?, z: r.f3()? };
            let point = r.f3()?;
            let tie = r.f64()?;
            let lines = r.segments()?;
            let arcs = r.arcs()?;
            let circles = r.circles()?;
            let count = r.u32()? as usize;
            let candidates = (0..count).map(|_| r.u32().map(|i| i as usize)).collect::<R<Vec<_>>>()?;
            r.finish()?;
            let selected = crate::sketch_pick::select(&frame, &lines, &arcs, &circles, &candidates, point, mode, tie).map_err(refused)?;
            Ok(std::iter::once(STATUS_OK).chain(selected.into_iter().map(|i| i as u32)).collect())
        }
        OP_SKETCH_EXTRUDE => {
            let key=BodyKey{id:[r.u32()?,r.u32()?,r.u32()?,r.u32()?],revision:r.u32()?};
            let frame=Affine{origin:r.f3()?,x:r.f3()?,z:r.f3()?};let depth=r.f64()?;let reverse=r.u32()?;
            if reverse>1{return Err(Fail::Malformed("sketch reverse flag".into()));}
            let lines=r.segments()?;let arcs=r.arcs()?;let circles=r.circles()?;let region=r.u32()? as usize;r.finish()?;
            let body=crate::sketch_regions::extrude(key,frame,&lines,&arcs,&circles,depth,reverse==1,region).map_err(refused)?;
            let words=wonky_wire::v3::encode(&body).map_err(|_|Fail::Refused("sketch-regions/wire".into()))?;
            decode_solid(&words)?;
            Ok(std::iter::once(STATUS_OK).chain(words).collect())
        }
        OP_CURVE_EXTRUDE => {
            let key = BodyKey { id: [r.u32()?, r.u32()?, r.u32()?, r.u32()?], revision: r.u32()? };
            let frame = Affine { origin: r.f3()?, x: r.f3()?, z: r.f3()? };
            let depth = r.f64()?;
            let reverse = r.u32()?;
            if reverse > 1 {
                return Err(Fail::Malformed("curve reverse flag".into()));
            }
            let entities = r.sketch3()?;
            let body = crate::curve_profile::build(key, frame, &entities, depth, reverse == 1).map_err(refused)?;
            let words = wonky_wire::v3::encode(&body).map_err(|_| Fail::Refused("curve-profile/wire".into()))?;
            decode_solid(&words)?;
            Ok(std::iter::once(STATUS_OK).chain(words).collect())
        }
        OP_CURVE_REGION => {
            let entities = r.sketch3()?;
            crate::curve_profile::profile(&entities).map_err(refused)?;
            Ok(text("{\"loops\":[{}],\"openWires\":0}".into()))
        }
        OP_PROFILE_REGION => {
            let circle=r.f3()?; let segments=r.segments()?; r.finish()?;
            crate::circle_profile::rectangle(&segments,circle).map_err(refused)?;
            Ok(text("{\"loops\":[{\"hole\":0},{\"circle\":0}],\"openWires\":0}".into()))
        }
        OP_PROFILE_EXTRUDE => {
            let key=BodyKey {id:[r.u32()?,r.u32()?,r.u32()?,r.u32()?],revision:r.u32()?};
            let frame=Affine {origin:r.f3()?,x:r.f3()?,z:r.f3()?};
            let circle=r.f3()?; let depth=r.f64()?;
            let reverse=r.u32()?; let disk=r.u32()?;
            if reverse>1 || disk>1 { return Err(Fail::Malformed("profile flags".into())); }
            let segments=r.segments()?;r.finish()?;
            let body=crate::circle_profile::extrude(key,frame,circle,&segments,depth,reverse==1,disk==1).map_err(refused)?;
            let words=wonky_wire::v3::encode(&body).map_err(|_|Fail::Refused("circle-profile/wire".into()))?;
            decode_solid(&words)?;
            Ok(std::iter::once(STATUS_OK).chain(words).collect())
        }
        OP_CIRCLE_REGION => {
            let center = [r.f64()?, r.f64()?]; let radius = r.f64()?; r.finish()?;
            wonky_sketch::circle_region::circle_region(center, radius).map_err(sketch_refusal)?;
            Ok(text("{\"loops\":[{\"circle\":0}],\"openWires\":0}".into()))
        }
        OP_SKETCH_POLYGON_REVOLVE => {
            let key=BodyKey {id:[r.u32()?,r.u32()?,r.u32()?,r.u32()?],revision:r.u32()?};
            let source=[r.u32()?,r.u32()?,r.u32()?,r.u32()?];
            let frame=Affine {origin:r.f3()?,x:r.f3()?,z:r.f3()?};
            let origin=r.f3()?;let axis=r.f3()?;let angle=r.f64()?;let segments=r.segments()?;r.finish()?;
            let body=crate::revolve_full::in_sketch(key,source,frame,origin,axis,&segments,angle).map_err(refused)?;
            let words=wonky_wire::v3::encode(&body).map_err(|e|Fail::Refused(format!("revolve/contract: {e:?}")))?;
            decode_any(&words)?;
            Ok(std::iter::once(STATUS_OK).chain(words).collect())
        }
        OP_FRAME_POLYGON_REVOLVE => {
            let key = BodyKey { id: [r.u32()?,r.u32()?,r.u32()?,r.u32()?], revision: r.u32()? };
            let source = [r.u32()?,r.u32()?,r.u32()?,r.u32()?];
            let frame = Affine { origin:r.f3()?,x:r.f3()?,z:r.f3()? };
            let angle = r.f64()?; let segments = r.segments()?; r.finish()?;
            let body = if angle == std::f64::consts::TAU { crate::revolve_full::build(key,source,frame,2,&segments,angle) } else { crate::revolve_sector::build(key,source,frame,&segments,angle) }.map_err(refused)?;
            let words = wonky_wire::v3::encode(&body).map_err(|e|Fail::Refused(format!("revolve/contract: {e:?}")))?;
            decode_any(&words)?;
            Ok(std::iter::once(STATUS_OK).chain(words).collect())
        }
        OP_FRAME_CIRCLE_REVOLVE => {
            let key = BodyKey { id: [r.u32()?,r.u32()?,r.u32()?,r.u32()?], revision: r.u32()? };
            let source = [r.u32()?,r.u32()?,r.u32()?,r.u32()?];
            let frame = Affine { origin:r.f3()?,x:r.f3()?,z:r.f3()? };
            let disk = wonky_sketch::circle_region::Disk { center:[r.f64()?,r.f64()?],radius:r.f64()? };
            let angle = r.f64()?; r.finish()?;
            let body = crate::revolve::circle_revolve_in_frame(key,source,frame,disk,angle).map_err(refused)?;
            let words = wonky_wire::v3::encode(&body).map_err(|e|Fail::Refused(format!("revolve/contract: {e:?}")))?;
            decode_any(&words)?;
            Ok(std::iter::once(STATUS_OK).chain(words).collect())
        }
        OP_CIRCLE_REVOLVE => {
            let key = BodyKey { id: [r.u32()?,r.u32()?,r.u32()?,r.u32()?], revision: r.u32()? };
            let source = [r.u32()?,r.u32()?,r.u32()?,r.u32()?];
            let sketch = Affine { origin:r.f3()?,x:r.f3()?,z:r.f3()? };
            let axis_origin=r.f3()?; let axis=r.f3()?;
            let disk=wonky_sketch::circle_region::Disk { center:[r.f64()?,r.f64()?],radius:r.f64()? };
            let angle=r.f64()?; r.finish()?;
            let body=crate::revolve::circle_revolve(&crate::revolve::CircleRevolve {key,source,sketch,axis_origin,axis,disk,angle}).map_err(refused)?;
            let words=wonky_wire::v3::encode(&body).map_err(|e|Fail::Refused(format!("revolve/contract: {e:?}")))?;
            decode_any(&words)?;
            Ok(std::iter::once(STATUS_OK).chain(words).collect())
        }
        OP_REGION => {
            let segments = r.segments()?;
            r.finish()?;
            let g = regions(&segments)?;
            let loops: Vec<String> = g
                .loops
                .iter()
                .map(|l| format!("{{\"uses\":[{}]}}", l.uses.iter().map(|(s, f)| format!("[{s},{f}]")).collect::<Vec<_>>().join(",")))
                .collect();
            Ok(text(format!("{{\"loops\":[{}],\"openWires\":{}}}", loops.join(","), g.open_wires)))
        }
        OP_REGION_PICK => {
            let mode = r.u32()?;
            if mode != crate::region_query::CONTAINS && mode != crate::region_query::CLOSEST {
                return Err(Fail::Malformed("region pick mode".into()));
            }
            let frame = Affine { origin: r.f3()?, x: r.f3()?, z: r.f3()? };
            let point = r.f3()?;
            let tie = r.f64()?;
            let segments = r.segments()?;
            let count = r.u32()? as usize;
            let candidates = (0..count).map(|_| r.u32().map(|i| i as usize)).collect::<R<Vec<_>>>()?;
            r.finish()?;
            // The regions are recomputed from the segments, as OP_PRISM does,
            // so the indices name the loops that extrusion will build.
            let g = regions(&segments)?;
            let selected = crate::region_query::select(&frame, &g.loops, &candidates, point, mode, tie).map_err(refused)?;
            Ok(std::iter::once(STATUS_OK).chain(selected.into_iter().map(|i| i as u32)).collect())
        }
        OP_LOFT => {
            let key=BodyKey {id:[r.u32()?,r.u32()?,r.u32()?,r.u32()?],revision:r.u32()?};
            let frame=Affine {origin:r.f3()?,x:r.f3()?,z:r.f3()?};
            let height=r.f64()?;
            let bottom=r.segments()?; let top=r.segments()?; r.finish()?;
            let loops=|segments: &[[f64;4]]| -> R<Vec<[f64;2]>> {
                let g=regions(segments)?;
                if g.loops.len()!=1 || g.open_wires!=0 {return Err(Fail::Refused("loft/one-closed-profile-required".into()));}
                Ok(g.loops[0].points.iter().map(|p|[p.x,p.y]).collect())
            };
            let body=crate::loft::build(key,[0;4],frame,&loops(&bottom)?,&loops(&top)?,height).map_err(refused)?;
            let words=wonky_wire::v3::encode(&body).map_err(|e|Fail::Refused(format!("loft/contract: {e:?}")))?;
            decode_body(&words)?;
            Ok(std::iter::once(STATUS_OK).chain(words).collect())
        }
        OP_PRISM => {
            let key = BodyKey { id: [r.u32()?, r.u32()?, r.u32()?, r.u32()?], revision: r.u32()? };
            let source = [r.u32()?, r.u32()?, r.u32()?, r.u32()?];
            let frame = Affine { origin: r.f3()?, x: r.f3()?, z: r.f3()? };
            let depth = r.f64()?;
            let reverse = match r.u32()? {
                0 => false,
                1 => true,
                _ => return Err(Fail::Malformed("reverse flag".into())),
            };
            let index = r.u32()? as usize;
            let segments = r.segments()?;
            r.finish()?;
            // The region is recomputed here from the segments; the host cannot
            // hand in a loop of its own.
            let g = regions(&segments)?;
            let region = g.loops.get(index).ok_or_else(|| Fail::Malformed("region index".into()))?;
            let body = match blind_prism(&Prism { key: key.clone(), source, frame, segments: &segments, region, depth, reverse }) {
                Ok(body) => body,
                Err(ExtrudeRefusal::LateralNormalNotExact { .. }) => {
                    // Replayed source profiles carry rational planes even when
                    // no binary64 side normal exists. Preserve the exact region
                    // selected above; never snap its endpoints or reuse a cache.
                    let lines = region.points.iter().enumerate().map(|(i, a)| {
                        let b = region.points[(i + 1) % region.points.len()];
                        [a.x, a.y, b.x, b.y]
                    }).collect::<Vec<_>>();
                    crate::arc_profile::build_in_source(key, source, frame, &lines, &[], depth, reverse).map_err(refused)?
                }
                Err(ExtrudeRefusal::Depth) => return Err(Fail::Refused("extrude/depth: not a positive finite length".into())),
                Err(ExtrudeRefusal::Contract(m)) => return Err(Fail::Refused(format!("extrude/contract: {m}"))),
            };
            let words = wonky_wire::v3::encode(&body).map_err(|e| Fail::Refused(format!("extrude/contract: {e:?}")))?;
            // The produced body must pass its own audit before it leaves Rust.
            decode_body(&words)?;
            Ok(std::iter::once(STATUS_OK).chain(words).collect())
        }
        OP_CERTIFIED_BOUNDS => {
            let words = r.words()?.to_vec();
            r.finish()?;
            let bounds = crate::broad_phase::bounds(&decode_solid(&words)?).map_err(refused)?;
            Ok(text(bounds.json()))
        }
        OP_MEASURE => {
            let body = r.words()?.to_vec();
            let map = match r.u32()? {
                0 => None,
                1 => {
                    let mut m = [[0.0; 4]; 3];
                    for row in &mut m {
                        for v in row.iter_mut() {
                            *v = r.f64()?;
                        }
                    }
                    Some(m)
                }
                _ => return Err(Fail::Malformed("map flag".into())),
            };
            let n = r.count(6)?;
            let probes: Vec<[f64; 3]> = (0..n).map(|_| r.f3()).collect::<R<_>>()?;
            // Optional face-class observation. Legacy requests and byte-bound
            // consumers retain their existing measurement schema unchanged.
            let surface_types = if r.at == r.words.len() { false } else {
                match r.u32()? {
                    1 => true,
                    _ => return Err(Fail::Malformed("surface types flag".into())),
                }
            };
            r.finish()?;
            let mut json = match decode_any(&body)? {
                HostBody::Solid(a) => a.measure(map, &probes),
                HostBody::Torus(a) => a.measure_json(map, &probes),
                HostBody::Sector(a) => a.measure_json(map, &probes),
            }.map_err(refused)?;
            if surface_types {
                let checked = wonky_wire::v3::decode(&body).map_err(|e| Fail::Malformed(format!("WC0 v3 body: {e:?}")))?;
                if json.pop() != Some('}') { return Err(Fail::Malformed("measurement JSON".into())); }
                json.push_str(&format!(",\"surfaceTypes\":{}}}", surface_types_json(checked.body())));
            }
            Ok(text(json))
        }
        OP_STL => {
            let deviation = r.f64()?;
            let n = r.count(1)?;
            let mut meshes = Vec::with_capacity(n);
            for _ in 0..n {
                let words = r.words()?;
                // Preserve the modelling-family audits. WC0's structural check
                // alone is not a proof of an embedded, oriented solid.
                decode_any(words)?;
                let checked = wonky_wire::v3::decode(words)
                    .map_err(|e| Fail::Malformed(format!("WC0 v3 body: {e:?}")))?;
                meshes.push(crate::mesh::tessellate(&checked, deviation).map_err(refused)?);
            }
            r.finish()?;
            let bytes = crate::mesh::binary_stl(&meshes, deviation).map_err(refused)?;
            let mut reply = Vec::with_capacity(2 + bytes.len().div_ceil(4));
            reply.extend([STATUS_OK, bytes.len() as u32]);
            for chunk in bytes.chunks(4) {
                let mut word = [0;4]; word[..chunk.len()].copy_from_slice(chunk);
                reply.push(u32::from_le_bytes(word));
            }
            Ok(reply)
        }
        OP_MESH => {
            let deviation = r.f64()?;
            let n = r.count(1)?;
            let mut bodies = Vec::with_capacity(n);
            for _ in 0..n {
                let words = r.words()?;
                decode_any(words)?;
                let checked = wonky_wire::v3::decode(words)
                    .map_err(|e| Fail::Malformed(format!("WC0 v3 body: {e:?}")))?;
                let mesh = crate::mesh::tessellate(&checked, deviation).map_err(refused)?;
                let vertices: Vec<f64> = mesh.vertices.iter().flatten().copied().collect();
                let triangles: Vec<String> = mesh.triangles.iter().flatten().map(|i| i.to_string()).collect();
                let faces: Vec<String> = mesh.faces.iter().map(|f| f.to_string()).collect();
                let edges: Vec<String> = mesh.edges.iter().map(|e| {
                    let ids: Vec<String> = e.vertices.iter().map(|i| i.to_string()).collect();
                    format!("{{\"vertices\":[{}],\"closed\":{}}}", ids.join(","), e.closed)
                }).collect();
                // Bind record staleness to exact WC0 endpoints, separately
                // from the tolerance-bounded display witnesses of those ends.
                let body = checked.body();
                let mut placements = std::collections::BTreeMap::new();
                let mut source_ends = Vec::new();
                for edge in &body.edges {
                    let mut points = Vec::new();
                    for id in &edge.vertices {
                        let vertex = &body.vertices[id.0 as usize];
                        let frame = crate::carriers::frame_placement(body, vertex.frame, &mut placements)
                            .map_err(|why| refused(Refused(format!("mesh/{why}"))))?;
                        let point = frame.apply(vertex.point.map(|v| v.get()), 1000., true)
                            .map_err(|_| refused(Refused("mesh/endpoint-world-range".into())))?;
                        points.extend(point);
                    }
                    source_ends.push(nums(&points));
                }
                bodies.push(format!(
                    "{{\"vertices\":{},\"triangles\":[{}],\"faces\":[{}],\"edges\":[{}],\"brepVertices\":{},\"edgeSourceEnds\":[{}]}}",
                    nums(&vertices), triangles.join(","), faces.join(","), edges.join(","), mesh.brep_vertices, source_ends.join(",")
                ));
            }
            r.finish()?;
            Ok(text(format!(
                "{{\"schema\":\"wonky-mesh/1\",\"deviationMm\":{},\"bodies\":[{}]}}",
                num(deviation), bodies.join(",")
            )))
        }
        OP_CARRIERS => {
            let n = r.count(1)?;
            let mut bodies = Vec::with_capacity(n);
            for _ in 0..n {
                let words = r.words()?;
                decode_any(words)?;
                let checked = wonky_wire::v3::decode(words)
                    .map_err(|e| Fail::Malformed(format!("WC0 v3 body: {e:?}")))?;
                bodies.push(crate::carriers::describe(checked.body()));
            }
            r.finish()?;
            Ok(text(format!("{{\"schema\":\"wonky-carriers/1\",\"bodies\":[{}]}}", bodies.join(","))))
        }
        OP_STEP => {
            let name = r.text()?;
            let n = r.count(2)?;
            let mut bodies = Vec::with_capacity(n);
            for _ in 0..n {
                let id = r.text()?;
                let words = r.words()?.to_vec();
                bodies.push((id, decode_any(&words)?));
            }
            r.finish()?;
            let torus = !bodies.is_empty() && bodies.iter().all(|(_,b)|matches!(b,HostBody::Torus(_)));
            let solids = bodies.iter().all(|(_,b)|matches!(b,HostBody::Solid(_)));
            let output = if torus {
                let named: Vec<_> = bodies.iter().filter_map(|(id,b)|if let HostBody::Torus(a)=b {Some((id.clone(),a))}else{None}).collect();
                crate::revolve_step::write(&named,&name)
            } else if !bodies.is_empty() && bodies.iter().all(|(_,b)|matches!(b,HostBody::Sector(_))) {
                let named: Vec<_> = bodies.iter().filter_map(|(id,b)|if let HostBody::Sector(a)=b {Some((id.clone(),a))}else{None}).collect();
                crate::revolve_sector_step::write(&named,&name)
            } else if solids {
                let named: Vec<_> = bodies.iter().filter_map(|(id,b)|if let HostBody::Solid(a)=b {Some((id.clone(),a.clone()))}else{None}).collect();
                solid::step(&named,&name)
            } else { Err(Refused("export/mixed-analytic-families".into())) };
            Ok(text(output.map_err(refused)?))
        }
        op => Err(Fail::Malformed(format!("unknown host op {op}"))),
    }
}

/// The addon entry: never panics through (the caller also catches unwinds).
pub fn host_op(words: &[u32]) -> Vec<u32> {
    let reply = |status: u32, s: String| std::iter::once(status).chain(s.chars().map(|c| c as u32)).collect();
    match wonky_curve::radical::guard(|| run(words)) {
        Ok(Ok(w)) => w,
        Ok(Err(Fail::Malformed(m))) => reply(STATUS_MALFORMED, m),
        Ok(Err(Fail::Refused(m))) => reply(STATUS_REFUSED, m),
        Err(r) => reply(STATUS_REFUSED, r.name().into()),
    }
}

#[cfg(test)]
mod host_registry_tests {
    use super::HOST_OPERATION_NUMBERS;
    use std::collections::BTreeMap;

    #[test]
    fn host_operation_numbers_are_unique() {
        assert!(!HOST_OPERATION_NUMBERS.is_empty(), "host operation registry is empty");
        let mut seen = BTreeMap::new();
        for &(name, number) in HOST_OPERATION_NUMBERS {
            assert!(number > 0, "{name} uses reserved host op 0");
            let previous = seen.insert(number, name);
            assert!(previous.is_none(), "duplicate host op {number}: {} and {name}", previous.unwrap_or(""));
        }
    }
}
