"""Update the self-contained CAD-Acid status page from a v2 scoreboard.

Usage: uv run --no-project python scripts/acid/build-status-page.py SCOREBOARD_JSON
The tracked page provides the 48 comparison modals and embedded V0 renders; this
builder deliberately preserves those artifacts and changes only verdict presentation.
"""

import argparse
from collections import Counter
from html import escape
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
PAGE = ROOT / "site/cad-acid-status.html"
KERNELS = ("wonky-rust", "onshape", "occt")
NAMES = ("wonky (Rust)", "Onshape", "build123d / OCCT")
TIERS = ("CORRECT", "TOLERANT", "REFUSED", "ERROR", "WRONG", "DISPUTED", "NOT_RUN", "UNVERIFIED")
MARKER = "/* v2 verdict presentation: generated by scripts/acid/build-status-page.py */"
CSS = """
/* v2 verdict presentation: generated by scripts/acid/build-status-page.py */
:root { --strict: #24623a; --practical: #116b67; }
h1 { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: clamp(2.2rem, 7vw, 3.8rem); font-weight: 800; letter-spacing: -.08em; }
.verdict.correct { background: #dceee0; border-color: #8bbb99; }
.verdict.tolerant { background: #cde9e6; border-color: #4b9f98; }
.verdict.refused, .verdict.not_run, .verdict.unverified { background: #eceff1; border-color: #c9cdd0; }
.verdict.error { background: #fff0d5; border-color: #e4be70; }
.verdict.wrong { background: #fbe2e0; border-color: #db8d87; }
.verdict.disputed { background-image: repeating-linear-gradient(135deg, #f1edfa, #f1edfa 6px, #e4dcf1 6px, #e4dcf1 12px); }
.score-pair { display: grid; gap: .08rem; min-width: 7rem; line-height: 1.25; }
.score-pair strong { font: 700 1.12rem/1.2 ui-monospace, SFMono-Regular, Menlo, monospace; font-variant-numeric: tabular-nums; }
.score-pair small { color: var(--muted); font-size: .7rem; }
.score-pair .strict-value { color: var(--strict); }
.score-pair .practical-value { color: var(--practical); }
.grid-head .score-pair { display: inline-flex; align-items: baseline; gap: .3rem; min-width: 0; }
.grid-head .score-pair strong { font-size: .8rem; }
.grid-head .score-pair small { font-size: .7rem; }
.status-entry .verdict { white-space: normal; overflow-wrap: anywhere; }
.grid-block:has(.grid-filter.v-correct:not(:checked)) .status-entry.v-correct,
.grid-block:has(.grid-filter.v-tolerant:not(:checked)) .status-entry.v-tolerant,
.grid-block:has(.grid-filter.v-not_run:not(:checked)) .status-entry.v-not_run,
.grid-block:has(.grid-filter.v-unverified:not(:checked)) .status-entry.v-unverified { display: none; }
.tolerance-citation { border-left: 3px solid #65aa9e; padding: .35rem .65rem; background: #f0f8f5; font-size: .84rem; line-height: 1.45; }
.tolerance-citation strong { display: inline-block; margin-right: .2em; }
.evidence-pending { display: block; margin-top: .4rem; font-size: .78rem; line-height: 1.4; color: var(--muted); border-left: 2px solid #80868b; padding-left: .5rem; }
@media (forced-colors: active) { .verdict.disputed { border-style: dashed; } .tolerance-citation { border-style: solid; } }
"""


def replace_one(text, pattern, replacement, description, flags=0):
    result, count = re.subn(pattern, replacement, text, count=1, flags=flags)
    if count != 1:
        raise ValueError(f"Expected exactly one {description}; found {count}")
    return result


def validate(data):
    if data.get("schema") != "wonky/cad-acid-scoreboard/2":
        raise ValueError("Expected wonky/cad-acid-scoreboard/2, not a legacy or unverified score")
    rows = {(r["kernel"], r["zone"]): r for r in data["zones"] if r["kernel"] in KERNELS}
    zones = sorted({zone for _, zone in rows})
    if len(zones) != 48 or len(rows) != 144:
        raise ValueError(f"Expected 48 zones x 3 kernels; got {len(zones)} zones and {len(rows)} rows")
    rules = {str(rule["id"]): rule for rule in data["toleranceRules"]["rules"]}
    if len(rules) != len(data["toleranceRules"]["rules"]):
        raise ValueError("Duplicate tolerance rule ID")
    for kernel in KERNELS:
        summary = data["kernels"][kernel]
        counts = Counter(rows[kernel, zone]["status"] for zone in zones)
        if summary["total"] != 48 or any(counts[tier] != summary["counts"].get(tier, 0) for tier in TIERS):
            raise ValueError(f"Scoreboard counts do not match rows for {kernel}")
        if summary["practical"] != counts["CORRECT"] + counts["TOLERANT"]:
            raise ValueError(f"Practical points inconsistent for {kernel}")
        if summary["strict"] != sum(rows[kernel, zone]["strictPoints"] for zone in zones):
            raise ValueError(f"Strict points inconsistent for {kernel}")
        for zone in zones:
            row = rows[kernel, zone]
            if row["status"] not in TIERS:
                raise ValueError(f"Unknown verdict {row['status']} for {kernel}/{zone}")
            ids = row.get("toleranceRuleIds", [])
            if row["status"] == "TOLERANT" and not ids:
                raise ValueError(f"TOLERANT {kernel}/{zone} is missing its rule citation")
            if row["status"] != "TOLERANT" and ids:
                raise ValueError(f"Non-tolerant {kernel}/{zone} has tolerance rules")
            if any(str(rule_id) not in rules for rule_id in ids):
                raise ValueError(f"Unknown rule for {kernel}/{zone}: {ids}")
    return rows, zones, rules


def badge(tier):
    return f'<span class="verdict {tier.lower()}">{tier}</span>'


def score_pair(summary):
    return ('<span class="score-pair">'
            f'<span><small>Strict</small> <strong class="strict-value">{summary["strict"]}/48</strong></span>'
            f'<span><small>Practical</small> <strong class="practical-value">{summary["practical"]}/48</strong></span>'
            '</span>')


def rule_text(rule):
    # Describe the actual frozen rule; do not infer tolerances from a badge.
    phenomenon = rule.get("phenomenon")
    acceptance = rule.get("acceptance", {})
    if isinstance(phenomenon, str) and isinstance(acceptance, dict):
        description = acceptance.get("description", "")
        first_conditions = ". ".join(description.split(". ")[:2]).rstrip(".")
        return f"{phenomenon} Acceptance: {first_conditions}." if first_conditions else phenomenon
    for key in ("summary", "description", "reason", "rationale", "title"):
        value = rule.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    raise ValueError(f"Tolerance rule {rule['id']} lacks a public rationale")


def pending_note(row, element="p"):
    reasons = row.get("evidencePending") or []
    if not reasons:
        return ""
    if not isinstance(reasons, list):
        raise ValueError("evidencePending must be a list of reasons")
    note = "; ".join(escape(str(reason)) for reason in reasons)
    return f'<{element} class="evidence-pending">Evidence pending (verdict unchanged): {note}</{element}>'


def render(data, source):
    rows, zones, rules = validate(data)
    if source.count('class="zone-modal"') != 48:
        raise ValueError("The source must retain all 48 comparison modals")
    if MARKER in source:
        source = replace_one(source, r"\n\s*" + re.escape(MARKER) + r"[\s\S]*?(?=\n</style>)", "", "old generated CSS")
    source = replace_one(source, r"</style>", lambda _: CSS + "\n</style>", "style block")

    code = (data.get("verification") or {}).get("code") or {}
    details = code.get("head") or ""
    tree_hash = code.get("treeSha256") or ""
    head = f"<code>{escape(details)}</code>" if details else "not recorded"
    tree_identity = f"<code>{escape(tree_hash)}</code>" if tree_hash else "not recorded"
    intro = ('<h2 id="status-report">Status report</h2>\n'
             f'<p>Rust tested code tree SHA-256: {tree_identity}. Git HEAD (which can omit uncommitted changes): {head}. '
             'Onshape and build123d / OCCT are frozen independent references, '
             'not live runs today. Scores use 48 zones per kernel; disputed zones stay in the denominator. '
             'The strict score follows the frozen v1 rules (including declared measurement tolerances). The practical score additionally accepts '
             'only rule-cited, documented tolerance behaviour; it never accepts a changed solid as correct.</p>\n')
    table = ('<div class="score-scroll"><table class="headline"><thead><tr>'
             '<th scope="col">Kernel</th><th scope="col">Strict / practical</th>'
             + ''.join(f'<th scope="col">{tier}</th>' for tier in TIERS)
             + '<th scope="col">Evidence</th></tr></thead><tbody>\n')
    for kernel, name in zip(KERNELS, NAMES):
        summary = data["kernels"][kernel]
        evidence = (f'code tree {escape(tree_hash[:12])}' if tree_hash and kernel == "wonky-rust" else
                    'code tree identity not recorded' if kernel == "wonky-rust" else
                    "frozen public Onshape document" if kernel == "onshape" else "frozen build123d twins")
        table += (f'<tr><th scope="row">{name}</th><td>{score_pair(summary)}</td>'
                  + ''.join(f'<td>{summary["counts"].get(tier, 0)}</td>' for tier in TIERS)
                  + f'<td>{evidence}</td></tr>\n')
    table += '</tbody></table></div>\n'
    source = replace_one(source, r'<h2 id="status-report">[\s\S]*?(?=<h3>V0 result galleries</h3>)',
                         lambda _: intro + table, "headline")
    source = replace_one(source, r'<h3>V0 result galleries</h3><p>[^\n]*</p>',
                         '<h3>V0 result galleries</h3><p>The embedded V0 solids are illustrative snapshots, '
                         'not evidence of a four-variant verdict. Each badge and score comes from the cited '
                         'scoreboard; a missing older preview does not mean the current run produced no solid. '
                         'Tap or click a tile for the larger three-kernel comparison and rule citation. '
                         'The three views use matching camera and scale within each zone; fine details may '
                         'not be visible at thumbnail resolution.</p>', "gallery description")
    source = source.replace('<span class="no-solid">No V0 solid</span>',
                            '<span class="no-solid">No V0 preview</span>')
    source = replace_one(source, r'<p class="gallery-legend">[^\n]*</p>',
                         ('<p class="gallery-legend">Green CORRECT means a frozen-v1 PASS or a predeclared expected refusal;'
                          'teal TOLERANT means a rule-cited practical acceptance, not exact agreement. '
                          'Red WRONG is a changed result, grey REFUSED is a safe refusal, amber ERROR an execution error, '
                          'and striped DISPUTED a suspended comparison. NOT_RUN and UNVERIFIED earn no points. '
                          'The badge states the four-variant verdict; tiles show V0 only. '
                          'Use the chips to filter each grid.</p>'), "gallery legend")

    def update_grid(match):
        index = update_grid.index
        update_grid.index += 1
        kernel = KERNELS[index]
        block = match.group(0)
        summary = data["kernels"][kernel]
        chips = []
        for tier in TIERS:
            count = summary["counts"].get(tier, 0)
            slug = tier.lower()
            disabled = ' filter-disabled' if not count else ''
            chips.append(f'<label class="filter-chip verdict {slug}{disabled}"><input class="grid-filter v-{slug}" '
                         f'id="f-{kernel}-{slug}" type="checkbox" checked{ " disabled" if not count else ""}>'
                         f'<span class="chip-text">{count} {tier}</span></label>')
        head = (f'<div class="grid-head"><h3>{NAMES[index]} · V0</h3><div class="grid-summary">'
                f'{score_pair(summary)} ' + ' '.join(chips) + '</div></div>')
        block = replace_one(block, r'<div class="grid-head">[^\n]*', lambda _: head, "grid heading")

        def update_tile(tile_match):
            tile = tile_match.group(0)
            zone = re.search(r'href="#zone-(AC\d{2})"', tile).group(1)
            tier = rows[kernel, zone]["status"]
            tile = re.sub(r'(<div class="status-entry )v-[a-z_]+',
                          lambda m: m.group(1) + 'v-' + tier.lower(), tile, count=1)
            return re.sub(r'<span class="verdict [a-z_]+">[^<]+</span>', badge(tier), tile, count=1)
        block, count = re.subn(r'<div class="status-entry [^\n]+', update_tile, block)
        if count != 48:
            raise ValueError(f"Expected 48 gallery tiles for {kernel}, got {count}")
        # Old audit numbers describe the strict-v1 verdict and cannot be used as v2 counts.
        block = re.sub(r'<div class="grid-audit">[^\n]*</div>', '', block)
        return block

    update_grid.index = 0
    source, count = re.subn(r'<div class="grid-block">[\s\S]*?(?=<div class="grid-block">|<div class="zone-modal")',
                            update_grid, source)
    if count != 3:
        raise ValueError(f"Expected 3 status grids, got {count}")

    def update_modal(match):
        line = match.group(0)
        zone = match.group(1)
        parts = []
        def update_column(column_match):
            index = len(parts)
            parts.append(True)
            row = rows[KERNELS[index], zone]
            section = column_match.group(0)
            section = replace_one(section, r'<span class="verdict [a-z_]+">[^<]+</span>',
                                  badge(row["status"]), "modal badge")
            v0 = row["variants"]["V0"]
            explanation = (f'Current four-variant verdict: {row["status"]}. '
                           f'Strict: {row["strictStatus"]}. V0 strict: {v0.get("strictStatus", v0["status"])}.')
            reasons = [v0.get("reason"), *(row.get("reasons") or [])]
            explanation += ''.join(f' {str(reason)}' for reason in reasons if reason)
            section = replace_one(section, r'<p class="kernel-detail">.*?</p>',
                                  lambda _: f'<p class="kernel-detail">{escape(explanation)}</p>',
                                  "current scoreboard explanation")
            section = re.sub(r'<p class="tolerance-citation">.*?</p>', '', section)
            section = re.sub(r'<p class="evidence-pending">.*?</p>', '', section)
            if row["status"] == "TOLERANT":
                references = '; '.join(
                    f'<strong>{escape(str(rule_id))}</strong> {escape(rule_text(rules[str(rule_id)]))}'
                    for rule_id in row["toleranceRuleIds"])
                citation = (f'<p class="tolerance-citation">Practical acceptance, not strict PASS. '
                            f'Strict verdict: {escape(row["strictStatus"])}. Rule: {references}</p>')
                section = section.replace('</section>', citation + '</section>')
            return section.replace('</section>', pending_note(row) + '</section>')
        line, column_count = re.subn(r'<section class="kernel-column [\s\S]*?</section>', update_column, line)
        if column_count != 3:
            raise ValueError(f"Expected 3 columns in modal {zone}, got {column_count}")
        return line
    source, count = re.subn(r'<div class="zone-modal" id="zone-(AC\d{2})"[^\n]*', update_modal, source)
    if count != 48:
        raise ValueError(f"Expected 48 comparison modals, got {count}")

    def update_matrix_row(match):
        line, zone = match.group(0), match.group(1)
        cells = []
        def update_cell(cell_match):
            index = len(cells)
            cells.append(True)
            row = rows[KERNELS[index], zone]
            cell = re.sub(r'<small class="evidence-pending">.*?</small>', '', cell_match.group(0))
            cell = re.sub(r'<span class="verdict [a-z_]+">[^<]+</span>', badge(row["status"]), cell, count=1)
            return cell.replace('</td>', pending_note(row, "small") + '</td>')
        line, cell_count = re.subn(r'<td>.*?</td>', update_cell, line)
        if cell_count != 3:
            raise ValueError(f"Expected 3 matrix cells for {zone}, got {cell_count}")
        return line
    source, count = re.subn(r'<tr><th scope="row">(AC\d{2})[^\n]*', update_matrix_row, source)
    if count != 48:
        raise ValueError(f"Expected 48 matrix rows, got {count}")
    source = replace_one(source, r'<h3>Every zone, side by side</h3>[\s\S]*?(?=<div class="score-scroll"><table class="matrix">)',
                         '<h3>Every zone, side by side</h3><p>Strict follows the frozen v1 rules: PASS and predeclared REFUSED_EXPECTED score one. Practical adds only TOLERANT cells backed by a named rule. A wrong solid is never TOLERANT. Frozen strict audit notes remain alongside affected cells as provenance, not practical verdicts: A = kernel issue (including safe refusal), B = documented tolerance behaviour, C = catalog, twin or measurement error. DISPUTED zones score zero for every kernel. All cells carry text labels as well as colour.</p><p class="status-legend">'
                         + ' '.join(badge(tier) for tier in TIERS) + '</p>\n', "matrix explanation")
    source = replace_one(source, r'<h3>(?:What the frozen non-PASS verdicts mean|What the scores do and do not claim)</h3>[\s\S]*?(?=<footer>)',
                         ('<h3>What the scores do and do not claim</h3><p>Strict retains the unmodified '
                          'catalog-v1 verdict, including known observer and exported-STEP limitations. '
                          'Practical accepts only the named tolerance rules in the modals. A rule describes '
                          'an observed difference; it does not certify general kernel correctness. '
                          'Frozen references were not rerun live, and no speed ranking is claimed here. '
                          '<a href="https://github.com/mneuhaus/wonky/actions/runs/36290097996">'
                          'An earlier independent Linux run</a> checked the prior Rust export at 24/48 strict; '
                          'it does not verify the revision on this page.</p>\n\n'),
                         "outdated narrative")
    source = replace_one(source, r'(<footer>[^\n]*CAD-Acid status report &middot; )27 September 2026',
                         r'\1scoreboard-backed', "outdated footer date") if '27 September 2026' in source else source
    if '<script' in source.lower() or len(source.encode("utf-8")) >= 500_000:
        raise ValueError("Status page must be script-free and under 500,000 bytes")
    return source


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("scoreboard", type=Path)
    parser.add_argument("--page", type=Path, default=PAGE)
    args = parser.parse_args()
    data = json.loads(args.scoreboard.read_text(encoding="utf-8"))
    source = args.page.read_text(encoding="utf-8")
    rendered = render(data, source)
    args.page.write_text(rendered, encoding="utf-8")
    print(f"Wrote {args.page}: {len(rendered.encode('utf-8'))} bytes; 48 comparison modals")


if __name__ == "__main__":
    main()
